### ISSUE TITLE
Get MPI to run again

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#17]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

Still open and still accurate. Confirmed against `main` at `d8b0e01`: there is no MPI anywhere in the build or the sources. `rg --word-regexp -i mpi` over the tree hits exactly two lines, neither of them code: a toolchain comment in `Makefile:144` about the NVIDIA HPC SDK, and a historical row in `CHANGELOG.md:20` (`| N | b5fc202 2022-06-29 | MPI working again, misses later columns in times_lost.dat |`). `CMakeLists.txt` has `option(ENABLE_OPENMP ...)` (line 75) and no `find_package(MPI ...)`; `src/CMakeLists.txt` lists no MPI source and links no MPI target. Every commit in the issue body's history table is a real ancestor of `origin/main` with the stated date and subject (`0ec5201` "Added MPI" 2022-03-03, `9fdaf88` "Slurm scripts" 2022-05-29, `d915c32` "Marconi SLURM" 2022-06-04, `b5fc202` "MPI working again" 2022-06-29, `7dd8310` "less MPI" and `785c72b` "remove MPI" both 2024-08-02). Nothing has re-added it since.

The issue body's sketch is broadly right and the insertion points it names still exist. Two things have changed since it was written: the result-array set has grown well beyond what `b5fc202` gathered, and there is a sampling hazard the old code did not face. Spec below.

## Purpose

SIMPLE is built to sit inside a stellarator-optimization loop, where the cost driver is the number of markers traced per candidate configuration. Markers are independent, so loss-fraction statistics are embarrassingly parallel, and the only reason the code is confined to one node today is the absence of a distribution layer. One MPI rank per node with OpenMP filling the node (the pattern the retired `RUN/Marconi/submit_mpi.slurm` used) turns a 4-node allocation into ~4x more markers at fixed wall time, which reduces the Monte-Carlo error on the confined fraction (`confined_fraction.dat`) as `1/sqrt(N)`.

## Current state

Tracing is a single OpenMP loop over the global particle index, `src/simple_main.f90:583-639`:

```fortran
        !$omp parallel firstprivate(norb) private(traj, times, i)
        allocate (traj(5, ntimstep), times(ntimstep))

        ! Independent markers have highly nonuniform trace costs. One-marker
        ! dynamic chunks keep unfinished work available to every thread instead
        ! of queueing it behind a pathological marker in a static block.
        !$omp do schedule(dynamic, 1)
        do i = 1, ntestpart
            if (allocated(particle_done)) then
                if (particle_done(i)) then
                    call progress_tick
                    cycle
                end if
            end if
```

The orchestration in `simple_main::main` (`src/simple_main.f90:108-262`) runs `read_config` -> `init_field` -> `params_init` -> sampling -> `init_bminmax` -> `init_counters` -> optional `read_restart_data` -> `progress_init` -> `trace_parallel(norb)` -> `progress_finalize` -> `write_output`.

The shared result arrays are module variables in `src/params.f90:38-44` and `:94-95`, allocated in `params_init` at `src/params.f90:495-503`:

- per-particle, length `ntestpart`: `times_lost`, `trap_par`, `perp_inv`, `orbit_exit_code`, `boundary_event_radial_residual`, `boundary_event_time_width`, `iclass(3, :)`, and `zend(zstart_dim1, ntestpart)` with `zstart_dim1 = 5` (`src/params.f90:29`);
- per-timestep, length `ntimstep`: `confpart_pass`, `confpart_trap` (real, incremented by `1.d0` under `!$omp atomic update` in `increase_confined_count`, `src/simple_main.f90:2104-2115`, with the increments themselves on lines `2110` and `2114`) and `unresolved_orbits` (integer, incremented under `!$omp atomic update` at `src/simple_main.f90:1258`, `1350`, `1468`).

`write_results` (`src/simple_main.f90:2195-2296`) writes, from those arrays:

- `times_lost.dat` — `i, times_lost(i), trap_par(i), zstart(1, i), perp_inv(i), zend(:, i)` (`:2220-2221`);
- `orbit_exit_code.dat` — `i, orbit_exit_code(i), times_lost(i), boundary_event_radial_residual(i), boundary_event_time_width(i)` (`:2235-2238`);
- `avg_inverse_t_lost.dat`, `confined_fraction.dat` (which divides by `resolved_count = ntestpart - unresolved_orbits(i)`, `:2254`), `unresolved_fraction.dat`, and conditionally `class_parts.dat` / `bminmax.dat`.

`write_output` (`:2173-2193`) additionally reduces the threadprivate counter `n_field_evaluations` (`src/field/field_can_base.f90:8-10`), prints it, calls `write_results`, and optionally writes `results.nc`.

### What the retired implementation actually did, and what must change

Read `git show b5fc202:SRC/simple.f90`. Two facts matter, and one widely repeated claim about it is wrong:

1. **It refused unequal partitions rather than corrupting them.** Lines 485-490 are an explicit hard stop:

   ```fortran
   if (mod(ntestpart, mpisize) /= 0) then
     print *, 'Number of test particles ', ntestpart, &
              ' no multiple of MPI size ', mpisize
     call finalize
     error stop
   endif
   ```

   The partition on lines 492-493 is `nfirstpart = mpirank * ntestpart/mpisize + 1`, `nlastpart = (mpirank+1) * ntestpart/mpisize`. (Note this is *not* the expression quoted in the issue body; Fortran evaluates it as `(mpirank*ntestpart)/mpisize`.) Combined with the guard, no marker was ever silently dropped. So remainder support is a **missing feature to add**, not a silent-corruption bug to avoid — but the new implementation should handle the remainder instead of inheriting the `error stop`, because `mod(ntestpart, nranks) /= 0` is the common case on a shared cluster.

2. **It gathered only three arrays.** `MPI_REDUCE` for `confpart_trap`/`confpart_pass` (lines 517-520) and `MPI_GATHER` for `times_lost`, `trap_par`, `perp_inv` (lines 522-533); the `iclass` gather is commented out behind a `! TODO FIX` (lines 534-539). `write_results` today also writes `zend(:, i)`, `orbit_exit_code(i)`, `boundary_event_radial_residual(i)` and `boundary_event_time_width(i)`, and divides by `unresolved_orbits`. A naive port of the `b5fc202` collective set would leave those columns holding whatever the local rank happened to have. `CHANGELOG.md:20` already records this as "misses later columns in times_lost.dat".

There is also a sampling hazard the old code did not face in this form. `sample_particles` (`src/simple_main.f90:829-877`) fills `zstart` through `samplers`, which draws from `random_number` (`src/samplers.f90:108`, `111`, `113`, `120`, `191`, `197`, `273`, `282`, `344`, `367`), and the seed is only pinned when `deterministic = .True.` (`src/params.f90:119`, `ran_seed = 42` at `:135`, `reset_seed_if_deterministic` at `:621-632`). With `deterministic = .False.` every rank would sample a *different* `zstart`, so rank 0's `start.dat` would not describe the markers the other ranks traced. `zstart` must be broadcast, not independently re-sampled.

## Reproduction / evidence

This is a capability gap, not a crash, so what follows is the verification recipe rather than a failing MRE.

Fixture: `test/golden_record/test_tokamak/simple.in`, which needs no equilibrium file:

```
&config
multharm = 3             ! Not used for TEST field but set for consistency
contr_pp = -1e10         ! Trace all passing particles
trace_time = 1d-4        ! slowing down time, s
sbeg = 0.3d0             ! starting s for particles
ntestpart = 32           ! number of test particles
isw_field_type = -1      ! TEST: analytic circular tokamak (no input files needed)
deterministic = .True.   ! reproducible random walk
/
```

Baseline (today, from the repo root; `CLAUDE.md:36` names `make CONFIG=Fast` as the preferred development build):

```bash
make CONFIG=Fast
mkdir -p /tmp/simple_ref && cp test/golden_record/test_tokamak/simple.in /tmp/simple_ref/
( cd /tmp/simple_ref && OMP_NUM_THREADS=4 "$OLDPWD/build/simple.x" simple.in )
```

Expected today, if you launch the current binary under `mpirun -np 2`: nothing partitions the loop, so each rank runs the *complete* 32-marker simulation and all ranks open the same result files in the same working directory. There is no speed-up, and `times_lost.dat` is written concurrently by every rank. (This is what the code structure implies; it is not an observation from a run, because `main` at `d8b0e01` contains no MPI calls at all.)

Expected after this issue: with `-DENABLE_MPI=ON`, `OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in` in a clean directory must produce `times_lost.dat`, `orbit_exit_code.dat` and `confined_fraction.dat` byte-identical to the serial run above.

Byte-identity is a legitimate criterion here, not wishful thinking. With `deterministic = .True.` and `swcoll = .False.` (`src/params.f90:114`) each marker's trajectory depends only on its own `zstart` column; `confpart_pass`/`confpart_trap` accumulate exact `+1.d0` increments whose sums are integers far below 2^53, so cross-rank summation order cannot change them; and every floating-point reduction over markers in `write_results` (for example `inverse_times_lost_sum`, `:2226-2227`) runs in a serial `do i = 1, ntestpart` loop on root *after* the gather, so its order is fixed regardless of rank count.

## Behaviour (BDD)

```gherkin
Scenario: Serial build is unchanged when MPI is off
  Given the repository is configured with -DENABLE_MPI=OFF (the default)
  When "make CONFIG=Fast test-fast" is run from the repository root
  Then "ldd build/simple.x" lists no libmpi
  And every test that passes at d8b0e01 still passes

Scenario: Four ranks reproduce the serial result bit-for-bit
  Given test/golden_record/test_tokamak/simple.in with ntestpart = 32 and deterministic = .True.
  And a build configured with -DENABLE_MPI=ON
  When "OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in" is run in a clean directory
  Then "cmp times_lost.dat <serial>/times_lost.dat" exits 0
  And "cmp confined_fraction.dat <serial>/confined_fraction.dat" exits 0
  And "cmp orbit_exit_code.dat <serial>/orbit_exit_code.dat" exits 0

Scenario: Marker count not divisible by rank count loses no markers
  Given a copy of test/golden_record/test_tokamak/simple.in with ntestpart = 10
  And a build configured with -DENABLE_MPI=ON
  When "OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in" is run in a clean directory
  Then the run does not abort (b5fc202 error-stopped on mod(ntestpart, nranks) /= 0)
  And times_lost.dat contains exactly 10 lines whose first field is 1,2,...,10 in order
  And no line of times_lost.dat has a second field equal to -1 (the untraced sentinel
      set at src/simple_main.f90:962)
  And "cmp times_lost.dat <serial ntestpart=10 run>/times_lost.dat" exits 0

Scenario: More ranks than markers is handled
  Given a copy of test/golden_record/test_tokamak/simple.in with ntestpart = 3
  When "OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in" is run in a clean directory
  Then the run completes and times_lost.dat contains exactly 3 lines
  And the rank that owns no markers does not hang in a collective

Scenario: Only rank 0 writes result files
  Given ntestpart = 32 and a build configured with -DENABLE_MPI=ON
  When "OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in" is run in an empty directory
  Then exactly one times_lost.dat, one start.dat and one confined_fraction.dat exist
  And exactly one line beginning " [progress]" ending the run is printed
  And that line reports "32/32", not "8/32"

Scenario: Non-deterministic sampling stays consistent across ranks
  Given test/golden_record/test_tokamak/simple.in edited to deterministic = .False.
  When "OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in" is run in a clean directory
  And the resulting start.dat is then re-run serially with startmode = 2 in a fresh directory
  Then the serial rerun's times_lost.dat is byte-identical to the 4-rank times_lost.dat
```

## Implementation plan

1. **Create `src/simple_parallel.F90`** — new module `simple_parallel`, unconditionally compiled, with all MPI bodies behind `#ifdef ENABLE_MPI`. Use the capital-`F90` suffix so preprocessing does not depend on the compiler-specific flags in `CMakeLists.txt` (`-cpp` at line 267 for GNU, `-Mpreprocess` at line 279 for NVHPC); `src/field.F90`, `src/get_canonical_coordinates.F90` and `src/util.F90` are the existing precedent. Public API, each a no-op or a trivial value in the serial build:
   - `parallel_init()`, `parallel_finalize()`
   - `parallel_rank()` (0 when serial), `parallel_size()` (1 when serial), `parallel_is_root()` (`.true.` when serial)
   - `parallel_partition(ntotal, ifirst, ilast)` — **block partition with remainder**:

     ```fortran
     base = ntotal/nranks
     rem  = mod(ntotal, nranks)
     ifirst = rank*base + min(rank, rem) + 1
     ilast  = ifirst + base - 1
     if (rank < rem) ilast = ilast + 1
     ```

     Every index in `1..ntotal` belongs to exactly one rank for any `ntotal >= 0`, `nranks >= 1`. Ranks with no work get `ilast = ifirst - 1`, so `do i = ifirst, ilast` is an empty loop — they must still enter every collective.
   - `parallel_bcast_real2d(a)` — `MPI_Bcast` from rank 0.
   - `parallel_reduce_sum_real1d(a)`, `parallel_reduce_sum_int1d(a)`, `parallel_reduce_sum_int64(x)` — `MPI_Reduce` onto root with `MPI_IN_PLACE` as the root's send buffer.
   - `parallel_collect_real1d(a)`, `parallel_collect_int1d(a)`, `parallel_collect_real2d(a)` — merge per-rank slices onto root.

   **Implement the collect with `MPI_Gatherv`, not a sum-reduction.** A sum-reduction would need a neutral element, and the arrays here do not have one: `times_lost` is initialised to the sentinel `-1.d0` (`src/simple_main.f90:962`), `boundary_event_*` to `-1d0` (`:964-965`), and `orbit_exit_code` carries integer codes. Build the `counts` and `displs` arrays on every rank by evaluating the same `parallel_partition` formula for `rank = 0 .. nranks-1`; for the 2D variants multiply both by the leading dimension (`zstart_dim1 = 5` for `zend`, `3` for `iclass`) — `a(:, ifirst:ilast)` is contiguous, so this is a plain gather of `size(a,1)*(ilast-ifirst+1)` elements. Gather into a temporary receive buffer allocated only on root and copy it back over `a`, rather than relying on `MPI_IN_PLACE` semantics for `MPI_Gatherv`, which are easy to get subtly wrong.
2. **Edit `src/CMakeLists.txt`** — add `simple_parallel.F90` to `set(SOURCES ...)`, before `params.f90` (line 59). In an `if(ENABLE_MPI)` branch add `target_link_libraries(simple PUBLIC MPI::MPI_Fortran)` and `target_compile_definitions(simple PUBLIC ENABLE_MPI)`.
3. **Edit `CMakeLists.txt`** — next to `option(ENABLE_OPENMP ... ON)` (line 75) add `option(ENABLE_MPI "Enable MPI distribution of markers." OFF)`; when set, `find_package(MPI REQUIRED COMPONENTS Fortran)`. Default OFF so CI, the golden-record contract and `pysimple` are untouched.
4. **Edit `src/simple_entry.f90`** — the whole file is currently a 7-line `subroutine simple_entry_main()` that does `call main`. Add `use simple_parallel, only: parallel_init, parallel_finalize`, `call parallel_init` before `call main`, `call parallel_finalize` after. Leave `app/simple.f90` unchanged.
5. **Edit `src/simple_main.f90`, `subroutine main` (`:108-262`)**:
   - after the sampling branch (`sample_particles` / `sample_particles_test_field` / `sample_spectre_surface`), call `parallel_bcast_real2d(zstart)` so all ranks trace the same markers regardless of `deterministic`;
   - guard the `save_starting_points` call sites (`src/samplers.f90:124`, `204`, `286`, `349` — the subroutine itself is at `:66-75` and opens `START_FILE = 'start.dat'` on unit 1) and `save_starting_points_test` (`src/simple_main.f90:918`) with `parallel_is_root()`, otherwise four ranks race on the same file;
   - guard the `print` statements in `print_parameters` (`:787-792`) with `parallel_is_root()`;
   - **after `call trace_parallel(norb)`, on every rank**: `parallel_collect_real1d` on `times_lost`, `trap_par`, `perp_inv`, `boundary_event_radial_residual`, `boundary_event_time_width`; `parallel_collect_int1d` on `orbit_exit_code`; `parallel_collect_real2d` on `zend`; the `int1d` 2D analogue on `iclass`; `parallel_reduce_sum_real1d` on `confpart_pass` and `confpart_trap`; `parallel_reduce_sum_int1d` on `unresolved_orbits`;
   - then `if (parallel_is_root()) call write_output`.
6. **Edit `src/simple_main.f90`, `trace_parallel` (`:583-639`)** — add `integer :: ifirst, ilast`, call `parallel_partition(ntestpart, ifirst, ilast)` before the `!$omp parallel` region, and change `do i = 1, ntestpart` (line 605) to `do i = ifirst, ilast`. Nothing in the loop body changes; `particle_done` and all result arrays stay globally indexed.
7. **Edit `src/simple_main.f90`, `write_output` (`:2173-2193`)** — `write_output` is now called on root only (step 5), so it must contain **no collectives**. Move the global field-evaluation count out: in `main`, after the existing collect block and *before* the `parallel_is_root()` guard, compute the OpenMP-reduced local `total_field_evaluations` and pass it through `parallel_reduce_sum_int64`, then hand the result to `write_output` as a new `integer(8), intent(in)` dummy argument that it prints. Putting the reduction inside a root-only `write_output` would hang every non-root rank.
8. **Edit `src/progress_monitor.f90`** — `progress_finalize` (`:43-49`) calls `emit(int(n_done_shared), ...)`, and `emit` (`:51-80`) prints `n_done` out of `n_total`, which would read `8/32` per rank. `progress_finalize` is called on every rank, so sum-reduce `n_done_shared` and the `diag_counters_total(id)` event totals used at `:66-73` onto root there, and print only on root. Do **not** touch `progress_tick` (`:33-41`): it must stay a bare atomic in the hot loop.
9. **Edit `src/restart.f90`** — `read_restart_data` (`:19-74`) opens `times_lost.dat` and `orbit_exit_code.dat` with `status='old'`, `action='read'`, so letting every rank read it is correct and needs no change; add a one-line comment recording that. `restore_confined_counts` (`:76-98`) loops `do i = 1, ntestpart` on every rank and adds `+1.0d0` into `confpart_pass`/`confpart_trap`, which would be multiplied by `nranks` by the reduction in step 5 — restrict that loop to `[ifirst, ilast]`.
10. **Hard-stop `output_orbits_macrostep` under MPI** — `trace_parallel` writes `orbits.nc` from inside the marker loop (`src/simple_main.f90:625-629`). With more than one rank this would have every rank writing the same file. In `main`, `if (output_orbits_macrostep .and. parallel_size() > 1)` print a clear message and `error stop`.
11. **Add `test/tests/test_mpi_partition.f90`** — pure serial unit test of `parallel_partition`, no `mpirun` needed: for `ntotal` in `{0, 1, 3, 7, 10, 32, 1000}` and `nranks` in `{1, 2, 3, 4, 8}`, assert that the intervals `[ifirst, ilast]` over `rank = 0 .. nranks-1` are pairwise disjoint and their union is exactly `1..ntotal`, and that sizes differ by at most 1. This pins the remainder and `nranks > ntotal` cases that `b5fc202` rejected outright.
12. **Add `test/tests/test_mpi_equivalence.sh`** (or a Python driver alongside `test/python/`) — copies `test/golden_record/test_tokamak/simple.in` into two fresh temporary directories, runs `simple.x` serially in one and under `mpirun -np 4` in the other, and `cmp`s `times_lost.dat`, `orbit_exit_code.dat`, `confined_fraction.dat`. Repeat with `ntestpart` patched to 10.
13. **Edit `test/tests/CMakeLists.txt`** — register both. Gate the `mpirun` test on `if(ENABLE_MPI AND MPIEXEC_EXECUTABLE)`, give it `LABELS "integration;mpi"`, `RUN_SERIAL TRUE` and its own `WORKING_DIRECTORY` (result-file collisions are a known hazard in this suite — see `b242fa6` "Serialize tests that share result files (#498)", 2026-07-17). Register `test_mpi_partition` with `LABELS "unit"` so it runs in `make test-fast` unconditionally.
14. **Follow-up PR: `.github/workflows/main.yml`** — add `libopenmpi-dev openmpi-bin` to the "Install system dependencies" step (line 45) and a job configuring `-DENABLE_MPI=ON` that runs `ctest -L mpi`. Do not add MPI to the existing deterministic/golden-record job; `make test-regression` must keep its current configuration. Splitting this out lets the main PR merge without an MPI runner.
15. **Edit `DOC/config.md` and `README.md`** — document `-DENABLE_MPI=ON` and the recommended hybrid launch (`--ntasks-per-node=1`, `OMP_NUM_THREADS=<cores per node>`), i.e. one rank per node with OpenMP inside.

No libneo change is required: `rg -l --word-regexp -i 'mpi_init'` over the libneo checkout returns nothing, and the distribution is entirely over SIMPLE's own marker loop.

## Acceptance criteria

- [ ] `make CONFIG=Fast test` passes with `ENABLE_MPI` unset (default OFF), with no failures that do not already fail at `d8b0e01`.
- [ ] `make CONFIG=Fast test-regression` produces unchanged golden records for every case under `test/golden_record/` (`albert`, `albert_coils`, `boozer`, `boozer_ncsx`, `canonical`, `classifier`, `classifier_combined`, `classifier_fast`, `collision`, `meiss`, `meiss_coils`, `test_tokamak`, `test_tokamak_classifier`).
- [ ] `test_mpi_partition` passes for every listed `(ntotal, nranks)` pair, including `mod(ntotal, nranks) /= 0` and `nranks > ntotal`.
- [ ] With `-DENABLE_MPI=ON` and `ntestpart = 32`: `cmp` exits 0 for `times_lost.dat`, `orbit_exit_code.dat` and `confined_fraction.dat` between `OMP_NUM_THREADS=1 mpirun -np 4 ./simple.x simple.in` and the `OMP_NUM_THREADS=4` serial run.
- [ ] Same three `cmp` checks exit 0 for `ntestpart = 10` with `-np 4` (remainder case), for `ntestpart = 3` with `-np 4` (idle-rank case), and for `-np 1`.
- [ ] A 4-rank run in an empty directory leaves exactly one `start.dat`, one `times_lost.dat` and one `confined_fraction.dat`.
- [ ] The final ` [progress]` line of a 4-rank `ntestpart = 32` run reads `32/32`.
- [ ] "Total field evaluations" printed by a 4-rank run of the `test_tokamak` fixture equals the value printed by the serial run of the same fixture. (Both trace the same 32 markers with the same seed; a mismatch means markers were traced twice or not at all.)
- [ ] `ldd build/simple.x` shows no MPI library in a default (`ENABLE_MPI=OFF`) build.

## References

- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, J. Comput. Phys. **403** (2020) 109065, doi:10.1016/j.jcp.2019.109065 — the integrators being parallelized (cited as [2] in `README.md`).
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Accelerated methods for direct computation of fusion alpha particle losses within stellarator optimization*, J. Plasma Phys. **86** (2020) 815860201, doi:10.1017/S0022377820000203 — the optimization-loop use case that motivates node-level scaling (cited as [1] in `README.md`).
- J. Varje, K. Särkimäki, J. Kontula, P. Ollus, T. Kurki-Suonio, A. Snicker, E. Hirvijoki, S. Äkäslompolo, *High-performance orbit-following code ASCOT5 for Monte Carlo simulations in fusion plasmas*, arXiv:1908.02482 — ASCOT5 solves the same statistical marker-following problem and was, per its abstract, "developed from ground up with an OpenMP-MPI hybrid paradigm", i.e. the same two-level decomposition proposed here.
- M. McMillan, S. A. Lazerson, *BEAMS3D Neutral Beam Injection Model*, Plasma Phys. Control. Fusion **56** (2014) 095019, doi:10.1088/0741-3335/56/9/095019 — the STELLOPT-family marker-following code, another instance of the same independent-marker workload.
- MPI-3.1 standard, Chapter 5 (Collective Communication), §5.5 "Gather" — defines `MPI_Gatherv`, the variant that accepts per-rank counts and displacements, which `MPI_Gather` in `b5fc202` could not.

## Scope and risk

One PR, roughly `size/M`: a new ~200-line `src/simple_parallel.F90`, ~70 lines of edits across `simple_main.f90`, `simple_entry.f90`, `progress_monitor.f90`, `restart.f90`, `samplers.f90`, plus build wiring and two tests. The CI-workflow change (step 14) is better split into a second PR so the first can merge without an MPI runner.

Main risks:

- **Collectives inside a root-only branch.** Step 7 exists precisely because the obvious placement of the field-evaluation reduction deadlocks. Audit every new collective: it must be reached by all ranks on all paths, including ranks whose partition is empty and the `error stop` paths in step 10.
- **Double-counting `confpart_*` on the restart path** (step 9).
- **Result-file races** if the `mpirun` test is not given its own `WORKING_DIRECTORY` and `RUN_SERIAL TRUE`.
- **Accidentally changing serial behaviour**, mitigated by the `ENABLE_MPI=OFF` default and the unchanged golden-record gate.

Related open issues:

- itpplasma/SIMPLE#42 (*Check parallelization of random numbers for collisional case*) becomes materially harder once ranks are added: `src/collis_alphas.f90:232` and `:266` draw from the global `random_number` stream, so a `swcoll = .True.` run will not be decomposition-invariant even with `deterministic = .True.`. Keep the equivalence test in step 12 on the collisionless `test_tokamak` case and treat per-marker RNG streams as #42's scope, ideally landing #42 first.
- itpplasma/SIMPLE#317 (*orbits.nc writes serialized by `!$omp critical` (was parallel in original design PR#182)*) touches the same output path; step 10 above deliberately hard-stops that feature under MPI rather than silently corrupting `orbits.nc`, and #317 should be resolved before MPI support for it is attempted.
