### ISSUE TITLE
Test metrics in simsopt

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#27]
Metrics:

1) Existing prompt losses
2) Fraction of ideal orbits from starting surfaces s = 0.4, 0.5
3) Think about bein even cleverer with "layered defense"

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

## Purpose

Still relevant, and it needs to become a concrete deliverable. The physics ingredients listed in the issue all exist in the code today; what does not exist anywhere in the repository is (a) a defined, reusable metric API and (b) any simsopt-facing optimization object. `rg -in 'Optimizable' .` returns zero hits across the whole tree.

For accuracy about the existing simsopt contact surface (this is broader than "just a download URL"):

- Test-fixture downloads from the simsopt repo: `test/conftest.py:22` (QA reactor-scale lowres), `test/python/CMakeLists.txt:4` (QH), `test/tests/CMakeLists.txt:18,20,232`, `test/golden_record/run_golden_tests.sh:59,66`, `README.md:229`, `test/test_data/get_test_data.sh:6`, `examples/run_example.sh:8`.
- A real but **disabled** simsopt consumer: `test/python/test_vmec.py:100` does `from simsopt.mhd import Vmec, vmec_compute_geometry`; its CTest registration is commented out at `test/python/CMakeLists.txt:8-15` ("Disabled test_vmec - uncomment to re-enable"). This is the only place in the tree that imports simsopt, and it is a geometry cross-check, not an optimization objective.
- `tools/quasr_json_to_boundary.py` parses simsopt serialization JSON (`simsopt_objs`) into a GVEC boundary file, without importing simsopt.

So: simsopt is a data source and a disabled test dependency, never an optimization target. The issue is open on its merits.

## Current state

Every ingredient exists; none is packaged as a metric.

- Topological ("ideal") classification is computed in `src/classification.f90`. `classification_result_t` (`src/classification.f90:34-41`) carries
  ```fortran
  logical :: passing ! Trapped (false) or passing (true)
  logical :: lost ! Orbit lost (true) or confined (false)
  integer :: fractal ! Fractal: 0=unclassified, 1=regular, 2=chaotic
  integer :: jpar ! J_parallel: 0=unclassified, 1=regular, 2=stochastic
  integer :: topology ! Topology: 0=unclassified, 1=ideal, 2=non-ideal
  integer :: exit_code ! Physical or numerical orbit termination
  ```
  and it is filled from `check_orbit_type` (`src/check_orbit_type.f90:20`) at banana tips:
  ```fortran
  call check_orbit_type(nturns,nfp_cot,fpr_in,ideal,ijpar,ierr_cot)   ! :350
  iclass(1,ipart) = ijpar                                             ! :352
  iclass(2,ipart) = ideal                                             ! :353
  ```
  Note the normalisation trap: this call sits inside the tip-detection branch, so `jpar`/`topology` are only meaningful for **trapped** orbits. Passing orbits skipped by `should_skip` (`src/params.f90:572-579`, true when `notrace_passing == 1` or `trap_par <= contr_pp`) are forced to `iclass(:,ipart) = 1` at `src/classification.f90:182` — i.e. they are *labelled regular by fiat*, not classified. Any metric that averages over all particles silently inherits that.
- Python access already exists: `pysimple.classify_fast(positions, nturns=8)` (`python/pysimple/__init__.py:987`) returns a dict with `jpar`, `topology`, `passing`, `lost`; `pysimple.sample_surface(n, s)` (`:300`) sets `sbeg(1)`, sets `ntestpart`, reallocates arrays and samples the surface; `pysimple.trace_parallel` (`:772`) returns `loss_times`. `examples/classify_fast.py` demonstrates the whole loop in ~25 lines.
- Prompt loss is only ever computed ad hoc: `examples/classification/plot_paper_results.py:176` (`prompt_loss = iclass_jpar == 0`), and `python/pysimple/engineering.py:41` mentions it in prose only. `print_table1` (`examples/classification/plot_paper_results.py:413-451`) computes regular-orbit fractions by re-reading `class_parts.dat` and `times_lost.dat` from disk — exactly the reusable function that should live in the library instead.
- There is no cascade and no per-metric error bar anywhere.

### Three state-handling constraints the implementation must respect

Both are verifiable in the current source and both invalidate the naive design:

1. **`trace_time` is fixed at `init()`.** `trace_parallel`'s own docstring (`python/pysimple/__init__.py:795-798`): "The trace time is determined by the `trace_time` parameter passed to `init()`. To change trace time, call `init()` again." So a prompt tier and a full tier at different trace times require two `init()` calls — or a single long trace whose `loss_times` are thresholded.
2. **The sampling RNG is only reset inside `init()`.** `reset_seed_if_deterministic` is called from `params_init` (`src/params.f90:206`, definition at `:621-632`, `ran_seed = 42` default at `:135`). `sample_surface` does *not* reset it, and the non-TEST path draws from the Fortran `random_number` stream via `Samplers%sample` (`src/samplers.f90`). Consequence: **calling `sample_surface(N, s)` twice in one process on a VMEC field returns different particle sets.** Common random numbers must therefore come from either re-`init()`-ing before each sample, or reusing one `positions` array across tiers. (The TEST-field path is different: it uses `np.random.default_rng(0)` when `deterministic`, `python/pysimple/__init__.py:123-127`, so it *is* repeatable without re-init.)
3. Minor, but it bites: `classify_fast` mutates global Fortran state (`params.nturns`, `params.fast_class = True`, `params.tcut = -1.0`, `python/pysimple/__init__.py:1028-1030`) and never restores it. A metrics module that calls `classify_fast` and then `trace_parallel` in one process must re-`init()` or explicitly reset `fast_class`.

## Reproduction / evidence

This is a feature request, so here is the verification recipe. Build and fetch the fixture the repo already uses (the Landreman–Paul 2021 QA reactor-scale lowres VMEC file, SHA256 pinned at `test/conftest.py:24`):

```bash
cd <repo root>
make CONFIG=Fast                                                  # CONFIG=Fast is valid: CMakeLists.txt:65
python -c "import test.conftest as c; c.download_wout_file()"     # -> test/test_data/wout.nc
```

Smallest case that demonstrates the metric is computable today (run from the repo root):

```python
import pysimple
pysimple.init('test/test_data/wout.nc', deterministic=True,
              trace_time=1e-2, isw_field_type=2)      # 2 = BOOZER, src/magfie.f90:43
p04 = pysimple.sample_surface(256, s=0.4)
res = pysimple.classify_fast(p04, nturns=8)
trapped = ~res['passing']
classified = trapped & (res['topology'] != 0)
f_ideal = (res['topology'][classified] == 1).sum() / classified.sum()
print(f_ideal, classified.sum(), trapped.sum())
```

Expected today: this runs and prints a number, but the number is not defined anywhere, has no error bar, silently depends on whether `should_skip` forced passing orbits to 1, and cannot be handed to an optimizer. Expected after this issue: `pysimple.metrics.ideal_orbit_fraction('test/test_data/wout.nc', s=0.4, n_particles=256)` returns a `MetricResult(value, stderr, n_trapped, n_passing, n_unclassified, fidelity, cost_proxy)`, reproducible on repeat.

**Analytic anchor for CI.** The analytic circular tokamak TEST field (`isw_field_type = -1`, `src/magfie.f90:43` and `magfie_test` at `src/magfie.f90:92-146`, already exercised by `test/golden_record/test_tokamak_classifier/simple.in`) has no `phi` dependence at all — `bmod = B0*(1 - r/R0*cos(theta))`, `bder(3) = 0`. It is exactly axisymmetric, so `J_parallel` is an exact invariant of the trapped orbits and every *classified* trapped orbit must come back `jpar == 1`. Use that as the hard CI assertion. Do **not** hard-code `topology == 1` as a theorem: `magfie_test` sets `hcurl = 0` with the in-source comment "simplified - not fully computed for TEST field", so the drift is deliberately incomplete there. Run the classifier on the TEST field once, record the observed `topology` histogram in the PR description, and pin *that* observed value as a regression guard.

## Behaviour (BDD)

```gherkin
Scenario: J_parallel is regular for every classified trapped orbit in axisymmetry
  Given pysimple.init(isw_field_type=-1, deterministic=True, trace_time=1e-2)
    And positions = pysimple.sample_surface(128, s=0.4)
  When ideal_orbit_fraction is evaluated on those positions with nturns=8
  Then every trapped orbit with jpar != 0 has jpar == 1
    And MetricResult.n_unclassified / MetricResult.n_trapped < 0.5
    And the observed topology histogram is recorded as the pinned regression value

Scenario: Prompt loss is a lower bound on total loss
  Given pysimple.init('test/test_data/wout.nc', isw_field_type=2,
        deterministic=True, trace_time=1e-2)
    And positions = pysimple.sample_surface(512, s=0.5)
  When loss_times = trace_parallel(positions)['loss_times'] is evaluated once
    And prompt = fraction(0 < loss_times < 1e-3)
    And total  = fraction(0 < loss_times < 1e-2)
  Then prompt <= total
    And both values lie in [0.0, 1.0]

Scenario: Metrics are reproducible when the seed is reset
  Given deterministic=True, ran_seed unchanged, identical n_particles, s, nturns
  When pysimple.init(...) then ideal_orbit_fraction(...) is run twice,
       each run starting from a fresh init() so params_init resets the seed
  Then the two MetricResult.value are bitwise identical
   # Note: WITHOUT the re-init the Fortran RNG stream has advanced and the
   # second sample_surface returns different particles (src/params.f90:206,621).

Scenario: Layered evaluation short-circuits a bad configuration
  Given a candidate whose prompt_loss_fraction(s=0.5, t_prompt=1e-3) exceeds
        the configured reject threshold 0.20
  When layered_metric(tiers=[prompt, ideal_fraction, full_loss]) is evaluated
  Then only the prompt tier is executed
    And MetricResult.fidelity == "prompt"
    And MetricResult.diagnostics["tiers_run"] == ["prompt"]

Scenario: simsopt objective is optional
  Given an environment without simsopt installed
  When `import pysimple.simsopt_objective` is executed
  Then it raises ImportError with an actionable message
    And `import pysimple` still succeeds
    And test/python/test_simsopt_objective.py skips via pytest.importorskip
```

## Implementation plan

1. **Create `python/pysimple/metrics.py`.** Pure Python on top of the existing API — no Fortran change is needed for the first three rungs. Define a frozen dataclass `MetricResult` with fields `value: float`, `stderr: float`, `n_particles: int`, `n_trapped: int`, `n_passing: int`, `n_unclassified: int`, `fidelity: str`, `cost_proxy: float`, `diagnostics: dict`. Implement:
   - `loss_fraction(vmec_file, s, n_particles, trace_time, integrator=pysimple.MIDPOINT)` — calls `pysimple.init(...)` (so the deterministic seed is reset), then `sample_surface` + `trace_parallel` (`python/pysimple/__init__.py:300,772`), counts `0 < loss_times < trace_time`, `stderr = sqrt(f(1-f)/N)`.
   - `prompt_loss_fraction(..., t_prompt=1e-3)` — two supported modes, both documented: cheap mode re-`init`s with `trace_time=t_prompt`; exact-bound mode reuses the `loss_times` of a longer trace and thresholds at `t_prompt`. Only the second guarantees `prompt <= total` by construction, so use it in the test. Document explicitly that "prompt" here means a trace-time cut, **not** `iclass == 0`; the `iclass_jpar == 0` convention at `examples/classification/plot_paper_results.py:176` is a plotting shorthand for "unclassified", not a loss criterion.
   - `ideal_orbit_fraction(..., nturns=8)` — wraps `classify_fast` (`python/pysimple/__init__.py:987`); normalise over `~results['passing'] & (topology != 0)` only, and report `n_unclassified = ((topology == 0) & ~passing).sum()` separately rather than folding it into the denominator. Add `regular_jpar_fraction` with the same shape, since `iclass(1,:)` is what `print_table1` uses. Both must document the `should_skip` caveat above.
   - `layered_metric(tiers, thresholds, ...)` returning the first tier that trips its threshold, with `diagnostics["tiers_run"]` and accumulated `cost_proxy`.
2. **Refactor `print_table1` (`examples/classification/plot_paper_results.py:413-451`) to call `pysimple.metrics`** instead of re-parsing `class_parts.dat`/`times_lost.dat`, so the library function is validated against the published Table 1 numbers rather than duplicating them.
3. **Create `python/pysimple/simsopt_objective.py`.** Guard the import (`try: from simsopt._core import Optimizable except ImportError: raise ImportError("pysimple.simsopt_objective requires simsopt; pip install pysimple[simsopt]")`). Define `SimpleLossObjective(Optimizable)` taking a `simsopt.mhd.Vmec` as a dependency, with `J()` calling `vmec.run()`, resolving `vmec.output_file`, and evaluating the configured metric **in a per-evaluation temporary working directory** — SIMPLE writes result files into the cwd (`start.dat` at `src/simple_main.f90:925`, `times_lost.dat` at `:2212`, `confined_fraction.dat` at `:2251`), so concurrent objective evaluations in one directory clobber each other. Add `dJ()` raising `NotImplementedError` and document that derivative-free / finite-difference use is intended; the differentiable route is #351. `test/python/test_vmec.py` is the existing precedent for the `Vmec(...)` call shape.
4. **Add `simsopt` as an optional extra in `pyproject.toml`** — there is currently no `[project.optional-dependencies]` table, so add `[project.optional-dependencies]\nsimsopt = ["simsopt"]`. Do **not** touch the hard `dependencies` list at `pyproject.toml:8`; CI must keep building without simsopt.
5. **Add `test/python/test_metrics.py`** covering the four non-simsopt scenarios above, using the session-scoped `vmec_file` fixture from `test/conftest.py:59` and the TEST field for the axisymmetric check.
6. **Add `test/python/test_simsopt_objective.py`** starting with `simsopt = pytest.importorskip("simsopt")`.
7. **Register both in `test/python/CMakeLists.txt`**, copying the `test_classification_api` block at lines 85-93: `LABELS "python;metrics;slow"`, `TIMEOUT 300`, `WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}`, and the same `ENVIRONMENT "PYTHONPATH=${CMAKE_BINARY_DIR}/python:${CMAKE_BINARY_DIR}:${CMAKE_SOURCE_DIR}/python"` string. Because these tests write result files into the working directory, add `RESOURCE_LOCK simple_result_files` — the same lock name introduced by `b242fa6` ("Serialize tests that share result files", #498) and currently used at `test/tests/CMakeLists.txt:829,839` — or give each test its own `tmp_path`.
8. **Add `DOC/confinement-metrics.md`** defining each metric formally: denominator convention (trapped-only, `should_skip` exclusion), `topology == 0` handling, error bar, cost proxy, default `t_prompt`, default `nturns`, default birth surfaces s = 0.4 and 0.5, and the cascade thresholds. This document is what makes the metric citable and comparable between runs.
9. **Add `examples/simsopt_metric_scan.py`** — the deliverable that actually answers this issue. Scan one boundary Fourier coefficient of the Landreman–Paul QA configuration over ~10 points, evaluate all three metrics at each point under common random numbers, and plot metric vs. parameter. This shows whether the classification metrics are smoother than raw loss fraction at fixed particle count, which is the open question the issue was raised to settle.

No libneo change is required; all touched code is SIMPLE-side Python plus test wiring.

## Acceptance criteria

- [ ] `make CONFIG=Fast && make test TEST=test_metrics` passes (`make test` filters via `ctest -R "$(TEST)"`, `Makefile:24`).
- [ ] Axisymmetric check: on the TEST field (`isw_field_type = -1`, `ntestpart=128`, `nturns=8`), **every** trapped orbit with `jpar != 0` has `jpar == 1`, and `n_unclassified/n_trapped < 0.5`.
- [ ] The observed TEST-field `topology` histogram is recorded in the PR body and pinned as a regression value in `test_metrics.py` (not asserted a priori as 1.0 — `magfie_test` sets `hcurl = 0`).
- [ ] `prompt_loss_fraction(s, t_prompt=1e-3) <= loss_fraction(s, trace_time=1e-2)` on `test/test_data/wout.nc` at s = 0.4 and s = 0.5, evaluated from a single shared `loss_times` array.
- [ ] Two runs that each start from a fresh `pysimple.init(..., deterministic=True)` return bitwise identical `MetricResult.value`.
- [ ] `layered_metric` executes only the first tier when its threshold trips, verified via `diagnostics["tiers_run"]`.
- [ ] `import pysimple` still succeeds with simsopt absent; `make test` is green on a simsopt-free runner and `test_simsopt_objective` reports SKIPPED there.
- [ ] `print_table1` in `examples/classification/plot_paper_results.py` reproduces its previous numbers after being rewired through `pysimple.metrics` (same inputs, same printed values).
- [ ] No change to any `test/golden_record/*` reference: `make test-regression` (`Makefile:77-78`) unchanged.
- [ ] `examples/simsopt_metric_scan.py` runs end to end and produces the metric-vs-parameter figure.

## References

- C. G. Albert, A. Buchholz, S. V. Kasilov, W. Kernbichler, K. Rath, *Alpha particle confinement metrics based on orbit classification in stellarators*, J. Plasma Phys. **89**(3), 955890301 (2023), doi:10.1017/S0022377823000351 — the definitional source for metrics 1 and 2. Citation taken verbatim from the header of `examples/classification/plot_paper_results.py:1-7`.
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Accelerated methods for direct computation of fusion alpha particle losses within stellarator optimization*, J. Plasma Phys. **86**, 815860201 (2020), doi:10.1017/S0022377820000203 — SIMPLE's own statement of the optimization-loop use case; listed as reference [1] at `README.md:306-307`.
- M. Landreman, E. Paul, *Magnetic fields with precise quasisymmetry for plasma confinement*, Phys. Rev. Lett. **128**, 035001 (2022) — source of the QA configuration used as the repository's test fixture.
- M. Landreman et al., *SIMSOPT: A flexible framework for stellarator optimization*, JOSS **6**(65), 3525 (2021) — the `Optimizable` / `J()` contract that step 3 must follow.
- D. Bindel, M. Landreman, M. Padidar, *Direct Optimization of Fast-Ion Confinement in Stellarators*, arXiv:2302.11369 (2023) — this is the paper linked from #39 (the issue text labels it "Paper of Rogerio", but the arXiv record lists Bindel, Landreman and Padidar). Companion code linked from #39: https://github.com/rogeriojorge/EPoptimization and https://github.com/mishapadidar/alpha_particle_opt. These are the external prior art for putting an alpha-loss target directly in a simsopt loop.
- J. Varje et al., *High-performance orbit-following code ASCOT5 for Monte Carlo simulations in fusion plasmas*, arXiv:1908.02482 (2019) — comparable orbit-following code used as a loss oracle in optimization workflows. (No claim is made here about whether ASCOT5 or BEAMS3D expose an orbit-classification proxy metric; that was not checked.)

## Scope and risk

One PR for steps 1, 2, 5, 7, 8 (the metric library and its tests) and a second PR for steps 3, 4, 6, 9 (the simsopt binding and the scan study); the second depends on the first. Risk is low and contained to new Python plus test registration — the only way this touches existing behaviour is step 2, which is why the acceptance list requires `print_table1` to reproduce its numbers. The real risks are (a) the global-state constraints listed above, which will silently produce non-reproducible numbers if ignored, and (b) the definitional question: the denominator convention (trapped only, `should_skip` exclusion, treatment of `topology == 0`) must be fixed in `DOC/confinement-metrics.md` before any optimization result is published, or two runs will not be comparable.

### Related issues

- itpplasma/SIMPLE#39 — *Test SIMPLE losses as optimization target in SIMSOPT* (same author krystophny, same assignee dannythecore, labelled `enhancement`). It carries the external references above. #39 is the "does it work as a target" study; **#27 is the metric-definition prerequisite**. Suggest keeping both and making #27 block #39, or merging #27 into #39 if only one is wanted.
- itpplasma/SIMPLE#351 — *Explore smooth Poincare-map proxy for alpha-loss optimization*. It makes exactly this issue's argument (hard labels — confined/lost, trapped/passing, regular/chaotic, prompt/non-prompt — are bad local derivative targets) and proposes the smooth successor. #27 delivers the hard-label baseline that #351 must beat.
- itpplasma/sensopt#64 — *Traced alpha-loss target evaluator with a fidelity ladder*. This is the "layered defence" of item 3, generalised, in the optimization repo. Its stated interface is `traced_loss(x, fidelity) -> (loss_fraction, stderr, diagnostics)`, and it should be the consumer of `pysimple.metrics`: align the `MetricResult` field names (`loss_fraction`, `stderr`, `diagnostics`, `cost_proxy`, `fidelity_level`) with it rather than inventing a second vocabulary.
