### ISSUE TITLE
Test SIMPLE losses as optimization target in SIMSOPT

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#39]
https://arxiv.org/abs/2302.11369

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

Still open and still worth doing. No SIMSOPT-driven optimization loop exists anywhere in the tree, and the enabling in-process Python API now does exist — so this is implementable rather than obsolete. But the repository is *not* in the state an implementer would assume, and the difference is load-bearing. See **Blocking prerequisite** below before writing any objective code.

What `rg -i simsopt` actually finds on `main` (15 files, none of them an optimization loop):

- wout download URLs: `test/conftest.py:22`, `test/python/CMakeLists.txt:3-6`, `examples/run_example.sh:8`, `README.md:229`, `CLAUDE.md:120`, `test/test_data/get_test_data.sh:5`, `examples/compare_ncsx_meiss_vmec_ck.py:27`, `test/golden_record/run_golden_tests.sh`, `test/tests/test_e2e_boozer_chartmap.py:42,56,69`, `test/tests/run_gvec_qa_roundtrip.py:21`, `test/tests/test_booz_xform_chartmap.py:41`, `test/tests/data/ncsx_freeboundary.PROVENANCE.md`
- `tools/quasr_json_to_boundary.py` — parses the `simsopt_objs` key of QUASR JSON by hand; never imports simsopt
- `test/python/test_vmec.py:100` — `from simsopt.mhd import Vmec, vmec_compute_geometry`. This is the **one real simsopt import in the repo**. It is a `# %%`-cell script, not a pytest module, and its ctest registration is commented out in `test/python/CMakeLists.txt:8-15`. It is a geometry cross-check, not an objective.

The old comparison scripts are genuinely gone: `1a5afd1` ("Add more comparisons to simsopt") and `7878586` ("wip: compare fields to simsopt") both touch only `draft/compare_simsopt.py`, which is absent from the tree. They were field comparisons, not objective evaluations.

One correction for the record: arXiv:2302.11369 is *Direct Optimization of Fast-Ion Confinement in Stellarators* by David Bindel, Matt Landreman and Misha Padidar — the same group as the second link (`mishapadidar/alpha_particle_opt`), not Jorge's. `rogeriojorge/EPoptimization` is a separate line of work.

## Purpose

SIMPLE exists to be fast enough to sit inside a stellarator optimization loop (Albert, Kasilov & Kernbichler, *J. Plasma Phys.* **86** (2020) 815860201; cited as `[1]` in `README.md:307`). That claim has never been tested from the outside in this repo. The questions are concrete: is the Monte-Carlo loss fraction smooth enough in boundary Fourier DOFs for a finite-difference optimizer to descend, do common random numbers actually hold across evaluations, and what particle count / trace time is needed before the gradient signal exceeds sampling noise. The answers decide whether alpha losses can be a direct target or whether a smooth proxy (#351) is mandatory.

## Blocking prerequisite: `deterministic=True` does not reset the RNG under `pysimple`

This is the single most important finding and it inverts the naive assumption.

`python/pysimple/__init__.py:274` carries the comment `# This calls reset_seed_if_deterministic() internally!` above the `params.params_init()` call at `:277`. **That comment is wrong.** Checked against the source:

- `subroutine params_init` spans `src/params.f90:261-366`. Its only `call` statements are `stevvo`, `init_batch` and `reallocate_arrays`. It never calls `reset_seed_if_deterministic`.
- Every call site of `reset_seed_if_deterministic` in the tree: `src/params.f90:206` (inside `subroutine read_config`, `src/params.f90:197-...`), `src/simple_main.f90:904` (inside `sample_particles_test_field`, TEST field only), `src/simple_main.f90:774` and `:1146` (both guarded by `if (swcoll)`), `src/diag/diag_orbit.f90:149`.
- `pysimple.init()` deliberately bypasses `read_config` — it sets `params` attributes directly (`python/pysimple/__init__.py:~230-238`) "replaces read_config, without file I/O" per its own docstring at `:167`. So the `read_config` reset never runs.
- The VMEC sampling path takes `samplers.sample(zstart)` (`python/pysimple/__init__.py:343-345`) → `sample_surface_fieldline_impl` (`src/samplers.f90:261-288`), which calls `random_number` twice per particle and resets nothing.
- `_sampling_rng()` (`python/pysimple/__init__.py:123-126`, `default_rng(0)` when `deterministic`) is only reached in the **TEST-field** branch of `sample_surface` (`:332`) and `sample_volume` (`:381`). It does not apply to VMEC or Boozer runs.

Net effect: under `pysimple`, with `deterministic=True` and a VMEC field, two successive `sample_surface` calls in one process draw from an *advancing* Fortran RNG stream and return different particles. The CRN property an optimizer needs is not there today. `test/python/test_simple_api.py:79-83` (`test_multiple_reinitializations`) only asserts that three `init()` calls on the same file do not crash — it never compares samples — so nothing catches this.

Fix it first, in Python only. `src/params.f90` is in the f90wrap source list (`python/CMakeLists.txt:86`) and `reset_seed_if_deterministic` is a public argument-less module procedure, so it should be reachable as `pysimple.params.reset_seed_if_deterministic()` exactly like the already-used `params.params_init()` / `params.apply_config_aliases()` / `params.reallocate_arrays()`. Verify with `python -c "import pysimple; print(hasattr(pysimple.params, 'reset_seed_if_deterministic'))"` before relying on it; if f90wrap did not export it, add it to the `params_wrapper` shim used elsewhere in `python/pysimple/__init__.py` rather than changing `src/`.

## Current state of the API

`python/pysimple/__init__.py` otherwise exposes the full evaluation chain:

- `init(vmec_file, *, ns_s, ns_tp, multharm, integmode, **param_overrides)` (`:154`) — sets `params.netcdffile` / `coord_input` / `field_input`, applies arbitrary `&config` overrides, calls `simple_main::init_field`, then `params_init()`.
- `sample_surface(n, s)` (`:300`), `sample_volume(n, s_inner, s_outer)` (`:351`).
- `trace_parallel(positions, integrator)` (`:772`) — returns a dict with `final_positions`, `loss_times`, and (when the backend exposes them) `trap_parameter`, `perpendicular_invariant` (`:856-870`).
- `current_vmec()` (`:1088`); `__all__` at `:1119-1141`.
- `python/pysimple/results.py` — `BatchResults` (`:16`) with `from_backend` (`:28`), `confined_mask` (`:61`), `skipped_mask` (`:65`), `lost_mask` (`:68`), already encoding the `loss_times < 0` skipped-passing sentinel.
- `"midpoint"` is a valid integrator alias (`_INTEGRATOR_ALIASES`, `:51-58`).

Re-initialization on a *new* file is supported: `init()` caches on a field key and rebuilds when any component changes:

```python
    field_key = (vmec_path, params.ns_s, params.ns_tp, params.multharm,
                 params.integmode,
                 int(_fortran_backend.velo_mod.isw_field_type))
    if not (_initialized and _tracer is not None and field_key == _field_key):
        _tracer = _fortran_backend.simple.tracer_t()
        _simple_main.init_field(...)
        _field_key = field_key
```
(`python/pysimple/__init__.py:246-259`)

`examples/simple_api.py` is the existing 18-line end-to-end template.

## What CRN can and cannot mean here

Worth stating precisely, because a naive acceptance criterion will be unsatisfiable. For a VMEC field, `sample_surface_fieldline_impl` (`src/samplers.f90:261-288`) draws `xi`, does `binsrc(volstart, 1, npoiper*nper, xi, i)`, and copies `zstart(1:3, ipart) = xstart(:, i)`; the second draw sets `zstart(5, ipart) = 2*(xi - 0.5)`.

- `volstart` and `xstart` are built by `init_starting_surf` (`src/samplers.f90:23-52`) from the *equilibrium's own* field line. So for two different wout files, the `(s, theta, phi)` columns **will legitimately differ** even under identical random streams. Do not assert equality on them.
- The pitch column `zstart(5, :)` is a pure function of the second uniform draw. Under true CRN it **must** match bit-for-bit across two equilibria at the same `ntestpart`. That is the checkable invariant.

## Reproduction / evidence

Feature request, not a bug — so this is a verification recipe. Build and fetch the fixture the way the repo does:

```bash
make CONFIG=Fast                       # CONFIG=Fast is a supported build type, CMakeLists.txt:65
python -m pytest test/python/test_simple_api.py -k init_basic   # session fixture downloads test/test_data/wout.nc
pip install "simsopt>=1.0"
```

The `vmec_file` session fixture (`test/conftest.py:56-67`) downloads the LandremanPaul2021 **QA** reactor-scale lowres wout to `test/test_data/wout.nc` and checks its SHA256 (`test/conftest.py:24`). Note that `examples/run_example.sh` downloads to `/tmp/simple_example/wout.nc` instead, and `test/python/CMakeLists.txt:3-6` downloads the **QH** file to the ctest binary dir — three different fixtures; be explicit about which one a measurement used.

Smallest case that exposes the prerequisite, run from the repo root:

```python
import numpy as np, pysimple

wout = "test/test_data/wout.nc"
pysimple.init(wout, deterministic=True, trace_time=1e-3, ntestpart=64, npoiper2=64)
a = pysimple.sample_surface(64, s=0.3)
pysimple.init(wout, deterministic=True, trace_time=1e-3, ntestpart=64, npoiper2=64)
b = pysimple.sample_surface(64, s=0.3)
print("CRN holds:", np.array_equal(a, b))   # expected TODAY: False
```

Expected on `d8b0e01`: `False`. After the prerequisite fix: `True`. Record both.

Once CRN holds, the objective probe:

```python
import numpy as np, pysimple
from simsopt.mhd import Vmec

vmec = Vmec("input.LandremanPaul2021_QA")   # NOTE: this repo ships no input.* file --
                                            # fetch one from simsopt's tests/test_files/
def loss_fraction(dofs, n=256, s=0.3, t=1e-3):
    vmec.x = dofs
    vmec.run()
    pysimple.init(vmec.output_file, deterministic=True, trace_time=t,
                  ntestpart=n, npoiper2=64)
    r = pysimple.trace_parallel(pysimple.sample_surface(n, s=s), integrator="midpoint")
    lt = r["loss_times"]
    return ((lt > 0.0) & (lt < t)).sum() / max((lt >= 0.0).sum(), 1)

x0 = vmec.x.copy()
print("f(x0) =", loss_fraction(x0), "repeat =", loss_fraction(x0))   # must be identical
h = 1e-3
for i in range(3):
    xp = x0.copy(); xp[i] += h
    print(i, (loss_fraction(xp) - loss_fraction(x0)) / h)
```

The finite differences are expected to be mostly exact zeros with occasional `1/n` jumps — the raw loss fraction is piecewise constant. That is the number this issue must produce and record, and it is the argument for a smoothed statistic.

## Behaviour (BDD)

```gherkin
Scenario: deterministic=True currently fails to give common random numbers
  Given a checkout at d8b0e01 and test/test_data/wout.nc
  When pysimple.init(wout, deterministic=True, ntestpart=64, npoiper2=64, trace_time=1e-3)
   And sample_surface(64, s=0.3) is called, then init and sample_surface are repeated identically
  Then np.array_equal(first, second) is False
   And this is recorded as the documented pre-fix baseline

Scenario: after the prerequisite fix, repeated evaluation is bit-identical
  Given the same steps with pysimple.params.reset_seed_if_deterministic() invoked inside init()
  When sample_surface(64, s=0.3) is called twice with an init() between
  Then np.array_equal(first, second) is True
   And trace_parallel(..., integrator="midpoint") returns loss_times arrays satisfying
       np.array_equal(lt_first, lt_second)

Scenario: common random numbers survive a change of equilibrium file
  Given two distinct wout files A and B, both with ntestpart=64 and deterministic=True
  When pysimple.init(A) then sample_surface(64, s=0.3), then pysimple.init(B) then sample_surface(64, s=0.3)
  Then the pitch row zstart[4, :] is equal elementwise between A and B (np.array_equal)
   And the (s, theta, phi) rows are NOT required to match, because init_starting_surf
       rebuilds xstart/volstart per equilibrium (src/samplers.f90:23-52)
   And pysimple.current_vmec() equals the path of B

Scenario: Loss fraction is monotone non-decreasing in trace_time
  Given test/test_data/wout.nc, ntestpart=512, s=0.3, deterministic=True, npoiper2=64
  When the objective is evaluated at trace_time in [1e-4, 1e-3, 1e-2]
  Then loss_fraction(1e-4) <= loss_fraction(1e-3) <= loss_fraction(1e-2)

Scenario: Raw loss fraction is flatter than the smoothed statistic
  Given 512 particles at s=0.3 on the QA reference and h=1e-3 on the first 5 boundary DOFs
  When both statistic="fraction" and statistic="smooth" are finite-differenced
  Then at least 3 of the 5 "fraction" differences are exactly 0.0
   And strictly fewer of the "smooth" differences are exactly 0.0

Scenario: The new tests are skipped, not failed, without simsopt
  Given simsopt is not importable
  When pytest runs test/python/test_simsopt_objective.py
  Then the simsopt-dependent tests report SKIPPED, the simsopt-free CRN tests still run,
       and the suite exit code is 0
```

## Implementation plan

0. **Prerequisite — `python/pysimple/__init__.py`.** Call `params.reset_seed_if_deterministic()` immediately after `params.params_init()` at `:277`, guarded by `hasattr(params, "reset_seed_if_deterministic")` with a clear fallback error if absent. Delete the false comment at `:274`. Add a regression test asserting the first two BDD scenarios. If `reset_seed_if_deterministic` turns out not to be f90wrap-exported, add a no-argument passthrough to the existing `params_wrapper` shim; do not change `src/params.f90` logic in this PR.
1. **`python/pysimple/optimization.py`** (new). `class AlphaLossObjective` with `__init__(self, vmec, *, s=0.3, n_particles=512, trace_time=1e-3, integrator="midpoint", npoiper2=64, ns_s=5, ns_tp=5, multharm=5, statistic="fraction")` and a `J(self)` method. `J()` runs `self.vmec.run()`, then `pysimple.init(self.vmec.output_file, deterministic=True, ...)`, `sample_surface`, `trace_parallel`, applies the `BatchResults` masks from `python/pysimple/results.py:61-68`, and returns the scalar. Support `"fraction"` (`lost_mask().sum() / n_valid`) and `"smooth"` (`mean(1 / max(t_loss, trace_time))`). Expose diagnostics (`n_lost`, `n_skipped`, `stderr = sqrt(p(1-p)/n)`) on `.last_diagnostics`. **No hard simsopt import at module scope** — import inside `try` / `except ImportError`.
2. **Same file, optional simsopt adapter.** `class SimpleAlphaLoss(Optimizable)` using `from simsopt._core import Optimizable`, constructed as `Optimizable.__init__(self, depends_on=[vmec])`, `J()` delegating to `AlphaLossObjective`, `recompute_bell()` invalidating the cache. Define the class only inside the successful-import branch; without simsopt, expose only `AlphaLossObjective`.
3. **`python/pysimple/__init__.py:1119-1141`** — add `'AlphaLossObjective'` (and `'SimpleAlphaLoss'` when importable) to `__all__`, importing lazily so plain `import pysimple` still works with no simsopt installed.
4. **`examples/simsopt_alpha_loss.py`** (new). The probe script above with `n_particles=256`, `trace_time=1e-3`; print `f(x0)`, the repeat, and the first 5 finite differences for both statistics. Exit 0 with a printed message when simsopt is missing, matching how `test/python/test_examples.py` subprocess-runs examples.
5. **`test/python/test_simsopt_objective.py`** (new). `pytest.importorskip("pysimple")` at module level (same as `test/python/test_examples.py:16`); `pytest.importorskip("simsopt")` only inside the tests needing a `Vmec`. Use the session `vmec_file` fixture from `test/conftest.py:56-67`. Implement the six scenarios. For the two-equilibrium scenario, do not re-solve VMEC: write a perturbed copy of `test/test_data/wout.nc` into `tmp_path` with `netCDF4` (already imported by `test/python/test_vmec.py:9`, though it is not in `pyproject.toml` `dependencies` — guard with `importorskip`), or use `params.vmec_RZ_scale` (`src/params.f90:175`).
6. **`test/python/CMakeLists.txt`** — register following the `add_test(NAME test_examples ...)` block near the end of the file: `LABELS "python;simsopt;slow"`, `TIMEOUT 600`, `ENVIRONMENT "PYTHONPATH=${CMAKE_BINARY_DIR}/python:${CMAKE_BINARY_DIR}:${CMAKE_SOURCE_DIR}/python"`, `WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}`. Note the working dir contains the **QH** wout downloaded at `test/python/CMakeLists.txt:3-6`; pass the QA fixture path explicitly if QA is what you measured. Add the example either as a second `add_test` or as a method on `test/python/test_examples.py`.
7. **`pyproject.toml`** — add `[project.optional-dependencies]` with `simsopt = ["simsopt"]`. Do **not** touch the `dependencies` list at `pyproject.toml:8`; the core build must stay simsopt-free.
8. **`README.md`** — a short subsection under the Python API showing the ten-line objective, cross-referencing `docs/boozer-chartmap-schema.rst` for the chartmap alternative to wout input.
9. **Report back in this issue** the measured numbers: the pre-fix and post-fix CRN booleans, loss fraction and its stderr at the QA reference, the finite-difference table for both statistics, and wall-clock per evaluation at 256/512/2048 particles. That measurement *is* the deliverable; the class is only the instrument.

No libneo change is required.

## Acceptance criteria

- [ ] `python -c "import pysimple; ..."` reproduction above prints `CRN holds: False` on `d8b0e01` and `True` after step 0; both are recorded in the issue.
- [ ] `make CONFIG=Fast && make test TEST=test_simsopt_objective` passes with simsopt installed.
- [ ] The same command exits 0 with simsopt *not* installed, with the simsopt-dependent tests reported SKIPPED and the CRN tests still executed.
- [ ] Two consecutive `J()` calls at identical DOFs return `loss_times` arrays satisfying `np.array_equal` (not `allclose`).
- [ ] `sample_surface` pitch row `zstart[4, :]` is `np.array_equal` across two different wout files at the same `ntestpart` and `deterministic=True`; the `(s, theta, phi)` rows are explicitly *not* asserted equal.
- [ ] `loss_fraction` is monotone non-decreasing across `trace_time in [1e-4, 1e-3, 1e-2]`.
- [ ] `make test-fast` and `make test-golden-fast` show no regression; nothing under `src/` changes in this PR.
- [ ] The issue carries a comment with the measured finite-difference table and per-evaluation timings.

## References

- D. Bindel, M. Landreman, M. Padidar, *Direct Optimization of Fast-Ion Confinement in Stellarators*, arXiv:2302.11369, DOI 10.1088/1361-6587/acd141 (Plasma Phys. Control. Fusion) — the paper linked in the issue; it shows direct trajectory-based optimization of alpha losses is feasible rather than requiring proxies. The specific smoothed statistic `mean(1/max(t_loss, t_max))` proposed above is an implementation choice here, not a verified quotation of their objective; check the paper before attributing it.
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Accelerated methods for direct computation of fusion alpha particle losses within stellarator optimization*, J. Plasma Phys. **86** (2020) 815860201, DOI 10.1017/S0022377820000203 — SIMPLE's own statement of the optimization-loop use case (`README.md:307-308`).
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, J. Comput. Phys. **403** (2020) 109065, DOI 10.1016/j.jcp.2019.109065 — the integrators in `src/orbit_symplectic.f90` (`README.md:310-311`).
- M. Landreman et al., *SIMSOPT: A flexible framework for stellarator optimization*, J. Open Source Software **6**(65) (2021) 3525 — the `Optimizable` / `Vmec` API this wraps.
- M. Landreman, E. Paul, *Magnetic fields with precise quasisymmetry for plasma confinement*, Phys. Rev. Lett. **128** (2022) 035001 — the configuration family the `wout_LandremanPaul2021_*` fixtures come from.
- A. Bader, D. T. Anderson, M. Drevlak, B. J. Faber, C. C. Hegna, S. Henneberg, M. Landreman, J. C. Schmitt, Y. Suzuki, A. Ware, *Energetic particle transport in optimized stellarators*, Nucl. Fusion **61** (2021), DOI 10.1088/1741-4326/ac2991 — comparable loss-fraction targets driven from STELLOPT.
- ASCOT5: J. Varje et al., *High-performance orbit-following code ASCOT5 for Monte Carlo simulations in fusion plasmas*, arXiv:1908.02482 — the usual guiding-centre/full-orbit loss evaluator plugged into optimizers. SIMPLE's argument against it here is the symplectic long-time integrator plus the in-process Python API. (BEAMS3D is the other common comparator; no verified citation is asserted for it.)

## Scope and risk

One PR, size `M`, tier `T1`: Python and tests only, no Fortran source change. The main risk is that step 0 does not work as expected — if `reset_seed_if_deterministic` is not f90wrap-exported, or if resetting it still does not make two `sample_surface` calls identical (e.g. because `init_field` or `init_starting_surf` itself consumes randomness), split that off as a separate SIMPLE bug issue for `pysimple` RNG state and block the rest on it. Everything downstream is meaningless without reproducible sampling.

Related open issues: itpplasma/SIMPLE#351 (smooth Poincaré-map proxy; it lists `**Related:** #39` in its body — the follow-on if the raw target proves too flat), itpplasma/SIMPLE#27 (test metrics in simsopt: existing prompt losses plus fraction of ideal orbits from starting surfaces `s = 0.4, 0.5`, which this evaluator should serve directly), itpplasma/SIMPLE#60 (add fields from SIMSOPT), and itpplasma/sensopt#64 (traced alpha-loss evaluator with a fidelity ladder — the natural consumer; keep the return signature compatible with its `traced_loss(x, fidelity) -> (loss_fraction, stderr, diagnostics)` contract, and note it explicitly calls for common random numbers within a local comparison, which is exactly the prerequisite above).
