### ISSUE TITLE
Handle error if simple.in does not exist

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#40]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

Still reproducible on `main`. `read_config` opens the config file with no `iostat`, so a missing or malformed `simple.in` terminates with a raw gfortran runtime error and a backtrace instead of a diagnostic. Spec below.

## Purpose

`simple.in` is the single entry point to every SIMPLE run: `app/simple.f90` -> `simple_entry_main` -> `simple_main::main` reads it before anything else happens (`src/simple_main.f90:142`). The first thing a new user does wrong is run `./build/simple.x` from the wrong directory, and the first thing an experienced user does wrong is typo a namelist key. Both currently produce a compiler-runtime backtrace that names *the Fortran source line*, not the user's file, and exits with code 2 with no indication that a config path can be passed as argv[1] (`src/simple_main.f90:133-138`). In an optimization loop, an unlabelled exit 2 from a wrapper script is indistinguishable from a physics failure. This is a small, self-contained usability and scriptability fix.

## Current state

`src/params.f90:197-236`:

```fortran
    subroutine read_config(config_file)
        character(256), intent(in) :: config_file

        open (1, file=config_file, status='old', action='read')
        read (1, nml=config)
        close (1)

        call apply_config_aliases
```

Three defects in four lines:

1. **No `iostat`/`iomsg` on the `open`** (line 200). A missing file aborts in the runtime library.
2. **No `iostat`/`iomsg` on the namelist `read`** (line 201). A typo'd key aborts the same way.
3. **Hardcoded unit `1`.** The rest of the codebase has moved to `newunit=` (`src/simple_main.f90:925`, `src/restart.f90:28`, `src/profiles.f90:48`); unit 1 is still used by `src/samplers.f90:58` and `:70` for `start.dat`, so this is a latent collision hazard.

**This is a regression, not an oversight.** Commit `15769cd` ("Open with status=old", 2025-04-02) *removed* the error handling that used to be here:

```
-    integer :: iostat
-    character(1024) :: iomsg
+    open(1, file=config_file, status='old', action='read')
-    open(1, file=config_file, recl=1024, iostat=iostat, iomsg=iomsg)
-    if (iostat /= 0) goto 666
-    read(1, nml=config, iostat=iostat, iomsg=iomsg)
-    if (iostat /= 0) goto 666
...
-    666 print *, iomsg
-    error stop
```

The fix below restores that intent in modern form (no `goto`, message on `error_unit`, usage hint).

Observed behaviour, reproduced with a standalone snippet using the identical `open` statement (gfortran):

```
At line 2 of file t.f90 (unit = 1)
Fortran runtime error: Cannot open file 'nope.in': No such file or directory

Error termination. Backtrace:
#0  0x7fd5e9227602 in ???
...
exit=2
```

and for a bad namelist key:

```
At line 5 of file t2.f90 (unit = 1, file = 'bad.in')
Fortran runtime error: Cannot match namelist object name bogus
```

The house style for config errors is already `error stop` with a message — `src/params.f90:217`, `:221`, `:225`, `:229`, `:233`, `:242`, `:247` all do exactly this (`error stop 'canonical map grid dimensions must be at least 6'`). This issue is about bringing the file-open path up to that same standard.

For contrast, the profiles reader already checks the open status but swallows the read status (`src/profiles.f90:48-52`):

```fortran
        open (newunit=unit, file=config_file, status='old', action='read', iostat=ios)
        if (ios /= 0) return

        read (unit, nml=profiles, iostat=ios)
        close (unit)
```

The silent return after the `open` is *correct* for `&profiles` (an optional namelist — defaults apply), but `ios` from the `read` is never tested, so a malformed `&profiles` block silently yields default profiles. Fix that too while you are in the area, with a warning rather than an abort, so the optional-namelist semantics are preserved. Note the caller is `read_profiles_config` in `src/simple_main.f90:794-800`, which delegates to `simple_profiles::read_profiles`.

Affected callers, all of which inherit the fix for free: `src/simple_main.f90:142`, `app/simple_diag_newton.f90:41`, `app/simple_diag_meiss.f90:33`, `app/simple_diag_albert.f90:33`, `app/simple_diag_traj.f90:62`, `app/simple_diag_orbit.f90:53`, `app/export_boozer_chartmap.f90:40`.

**Existing test coverage.** Ten test files under `test/tests/` already call `read_config`, all of them with a config file that exists and parses (`test_deterministic_seed.f90`, `test_coord_trans.f90`, and eight under `test/tests/field_can/`). None exercises a missing or malformed config file, so the failure path is entirely untested. `test/tests/test_deterministic_seed.f90` is the closest precedent and the right model to copy: it writes its own `.in` fixture at runtime, calls `read_config`, and deletes the file afterwards.

## Reproduction / evidence

```bash
cd /path/to/SIMPLE
make CONFIG=Fast
mkdir -p /tmp/simple_missing_config && cd /tmp/simple_missing_config
/path/to/SIMPLE/build/simple.x ; echo "exit=$?"
```

Observed:

```
SIMPLE version ...
At line 200 of file .../src/params.f90 (unit = 1)
Fortran runtime error: Cannot open file 'simple.in': No such file or directory

Error termination. Backtrace:
#0 ...
exit=2
```

Expected after the fix (stderr, no backtrace):

```
ERROR: cannot open configuration file 'simple.in'
       Run from a directory containing simple.in, or pass a path:
         ./build/simple.x /path/to/config.in
exit=1
```

Malformed-namelist case, using a real fixture:

```bash
mkdir -p /tmp/simple_bad_config && cd /tmp/simple_bad_config
sed 's/^ntestpart = .*/ntestpart_typo = 4/' /path/to/SIMPLE/test/golden_record/boozer/simple.in > simple.in
/path/to/SIMPLE/build/simple.x ; echo "exit=$?"
```

Observed: `Fortran runtime error: Cannot match namelist object name ntestpart_typo` + backtrace, exit 2.
Expected: `ERROR: failed to read &config namelist from 'simple.in'` followed by the compiler `iomsg` text, exit 1.

(`test/golden_record/boozer/simple.in` exists in the repo and is a complete, valid `&config` block; the repo-root `simple.in` works equally well as the base. Confirm the exact spelling of the key you rewrite with `grep -n ntestpart test/golden_record/boozer/simple.in` before running the `sed`.)

## Behaviour (BDD)

```gherkin
Scenario: Missing default config file
  Given an empty working directory containing no file named "simple.in"
  When I run "./build/simple.x"
  Then stderr contains "cannot open configuration file 'simple.in'"
  And stderr contains the string "pass a path"
  And stdout/stderr contain no line matching "Fortran runtime error"
  And the process exit status is 1

Scenario: Missing explicitly named config file
  Given an empty working directory
  When I run "./build/simple.x does_not_exist.in"
  Then stderr contains "cannot open configuration file 'does_not_exist.in'"
  And the process exit status is 1

Scenario: Malformed &config namelist
  Given a file "simple.in" copied from test/golden_record/boozer/simple.in
  And the key "ntestpart" in it renamed to "ntestpart_typo"
  When I run "./build/simple.x"
  Then stderr contains "failed to read &config namelist from 'simple.in'"
  And stderr contains the compiler iomsg text for the unmatched object name
  And the process exit status is 1

Scenario: Valid config still runs unchanged
  Given the working directory is test/golden_record/boozer
  When I run "./build/simple.x simple.in"
  Then the run completes normally
  And "confined_fraction.dat" is written
  And the golden-record comparison for case "boozer" passes unchanged

Scenario: Optional &profiles namelist absent
  Given a "simple.in" that contains a valid &config block and no &profiles block
  When I run "./build/simple.x"
  Then the run completes normally using default profile parameters
  And no error or warning is printed about &profiles
```

## Implementation plan

1. **`src/params.f90`** — rewrite `read_config` (line 197). Add `error_unit` to the module's existing `iso_fortran_env` import at line 2 (currently `use, intrinsic :: iso_fortran_env, only: int8, int64`); extend that line rather than adding a second `use`. Replace lines 200-202 with:

   ```fortran
   integer :: unit, ios
   character(512) :: iomsg_text
   logical :: file_exists

   inquire (file=config_file, exist=file_exists)
   if (.not. file_exists) then
       write (error_unit, '(A)') "ERROR: cannot open configuration file '" &
           //trim(config_file)//"'"
       write (error_unit, '(A)') '       Run from a directory containing '// &
           'simple.in, or pass a path:'
       write (error_unit, '(A)') '         ./build/simple.x /path/to/config.in'
       error stop 1
   end if

   open (newunit=unit, file=config_file, status='old', action='read', &
         iostat=ios, iomsg=iomsg_text)
   if (ios /= 0) then
       write (error_unit, '(A)') "ERROR: cannot open configuration file '" &
           //trim(config_file)//"': "//trim(iomsg_text)
       error stop 1
   end if

   read (unit, nml=config, iostat=ios, iomsg=iomsg_text)
   if (ios /= 0) then
       close (unit)
       write (error_unit, '(A)') "ERROR: failed to read &config namelist "// &
           "from '"//trim(config_file)//"': "//trim(iomsg_text)
       error stop 1
   end if
   close (unit)
   ```

   The declarations go at the top of the procedure, after `character(256), intent(in) :: config_file`, per house style. `trim()` is required throughout because the dummy is fixed-length `character(256)`.

   The `inquire` is kept separate from the `open` because it lets the not-found case carry the usage hint while genuine I/O failures (permissions, EIO) report the compiler's `iomsg`. Use `error stop 1` with an **integer literal** stop code, not a runtime character expression: NVHPC is a supported compiler here (`CMakeLists.txt:40,90,134`) and no `-std=` is set, so stay inside F2008 for the stop code and put the text on `error_unit` yourself.

2. **`src/profiles.f90`** — in `read_profiles` (line 44), keep `if (ios /= 0) return` after the `open` at line 48 (the `&profiles` namelist is genuinely optional), but change the `read` at line 51 so a nonzero `ios` writes a warning to `error_unit` naming the file and the `iomsg`, then falls back to defaults. Add `iomsg=` to that `read`. Do **not** `error stop` here: that would break every existing `simple.in` that omits `&profiles`.

3. **`src/samplers.f90`** — `load_starting_points` (line 54) opens its input with `open (1, file=filename, recl=1024)` at line 58, i.e. default `status='unknown'`. A missing input file is therefore *created empty* and the subsequent `read` dies with `End of file`. This path is reached from `sample_particles` in `src/simple_main.f90:852` when `startmode == 2` (which passes `START_FILE = 'start.dat'`, `src/samplers.f90:7`), from `startmode == 3` via `special_ants_file`, and from `src/samplers.f90:364,366` for the batch/restart files. Switch to `newunit=`, `status='old'`, `iostat=`, and emit the same style of message naming the file and the active `startmode`. The sibling opens with hardcoded unit 1 are at `:70` (`save_starting_points`, write path), `:399` (`START_FILE_ANTS = 'start_ants.dat'`), and `:403` (`START_FILE`). This is the same defect class and worth folding into one PR; if the reviewer prefers, split it into a follow-up issue and keep this one to `read_config`.

4. **`test/tests/test_config_errors.f90`** (new) — a Fortran unit test that calls `read_config` on a deliberately absent path. Declare the argument as a `character(256)` local variable and assign the path into it (do not pass a character literal: the dummy is fixed-length `character(256)`). Because the failure path is `error stop`, drive it as a *process-level* test rather than an assertion: register it in CMake with `WILL_FAIL TRUE` (the pattern already used at `test/tests/CMakeLists.txt:669` and `test/tests/magfie/CMakeLists.txt:98`).

5. **`test/tests/CMakeLists.txt`** — register the new executable and tests, following the `test_util_simple` block at lines 492-494:

   ```cmake
   add_executable(test_config_errors.x test_config_errors.f90)
   target_link_libraries(test_config_errors.x simple)
   add_test(NAME test_config_missing_file COMMAND test_config_errors.x)
   set_tests_properties(test_config_missing_file PROPERTIES
       LABELS "unit" WILL_FAIL TRUE)
   ```

   Add two CLI-level tests that assert on the *message*, following the `PASS_REGULAR_EXPRESSION` pattern at line 808 and the `simple.x`-invoking `add_test` at lines 800-805. Give each its own `WORKING_DIRECTORY` under `${CMAKE_CURRENT_BINARY_DIR}` so they cannot pick up a stray `simple.in` — and create that directory at configure time, or the test errors out before it runs:

   ```cmake
   file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/config_errors)

   add_test(NAME test_config_missing_message
       COMMAND $<TARGET_FILE:simple.x> definitely_absent_config.in
       WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/config_errors)
   set_tests_properties(test_config_missing_message PROPERTIES
       LABELS "unit"
       PASS_REGULAR_EXPRESSION "cannot open configuration file"
       FAIL_REGULAR_EXPRESSION "Fortran runtime error"
       TIMEOUT 60)
   ```

   Add a second such test that `configure_file`s a corrupted copy of `test/golden_record/boozer/simple.in` into the same directory and asserts `PASS_REGULAR_EXPRESSION "failed to read &config namelist"`. Note that when both are set, CTest applies `FAIL_REGULAR_EXPRESSION` first, so the test passes only if the good message appears *and* the runtime backtrace does not.

6. **`DOC/config.md`** — one short bullet (the file is a bullet list of config semantics) documenting the config-file resolution rule (argv[1], else `simple.in` in the current directory) and the fact that both failure modes now exit 1 with a message on stderr. This is the contract scripts and optimizer wrappers will depend on.

No libneo change is needed: `read_config` and the `&config` namelist are entirely SIMPLE-local (`src/params.f90`), unaffected by the libneo field-abstraction move in `cb64f23`/`29c6427` ("Use libneo field abstraction and boozer_sub; drop SIMPLE copies", #389).

## Acceptance criteria

- [ ] `make CONFIG=Fast` builds clean, no new warnings from `src/params.f90` or `src/profiles.f90`.
- [ ] `make test TEST=test_config_missing_message` passes; the run prints `cannot open configuration file` and prints **no** line containing `Fortran runtime error`.
- [ ] `make test TEST=test_config_bad_namelist` passes and the output names both `simple.in` and the offending namelist object.
- [ ] `./build/simple.x` in an empty directory exits with status **1** (not 2, not 0) and emits no backtrace.
- [ ] `./build/simple.x definitely_absent.in` names `definitely_absent.in`, not `simple.in`, in the error text.
- [ ] `grep -n "open (1," src/params.f90` returns nothing — the hardcoded unit is gone.
- [ ] A `simple.in` with a valid `&config` and no `&profiles` block still runs and still uses default profile parameters (no new error, no new warning).
- [ ] The ten existing tests that call `read_config` still pass unchanged (`rg -l read_config test/tests`).
- [ ] `make test` passes with no new failures.
- [ ] `make test-regression` shows **no** change in any golden-record case (`albert`, `albert_coils`, `boozer`, `boozer_ncsx`, `canonical`, `classifier`, `classifier_combined`, `classifier_fast`, `collision`, `meiss`, `meiss_coils`, `test_tokamak`, `test_tokamak_classifier`) — this change must be bit-identical on all valid inputs.
- [ ] The PR fills the project pull request template and states its risk tier per `docs/review-policy.md`. The blast radius is the config-read failure path only, so the operative evidence requirement is the unchanged golden records above.

## References

No specific literature reference; this is an implementation detail internal to the code. The mechanisms used are standard Fortran: `iostat=`/`iomsg=` specifiers on `OPEN` and namelist `READ`, and `ERROR STOP` with an integer stop code (F2008; a *non-constant* character stop code needs F2018 and is deliberately avoided here for NVHPC portability).

Related work flagged by the triage pass. These issue numbers could **not** be verified from the read-only checkout — confirm them before cross-linking:

- itpplasma/libneo#49 — reported as the same defect class (unchecked open status) in the shared library.
- itpplasma/SIMPLE#173 — reported as a configuration-system refactor that rewrites this same routine. If both are real, this issue should land **first**: it is small and a strict improvement, and the refactor should then preserve the error contract established here rather than re-derive it.

## Scope and risk

Single PR, small: one procedure rewritten in `src/params.f90`, a warning added in `src/profiles.f90`, one new test file, and CMake wiring. Risk is confined to the failure path — on every valid input the behaviour must be bit-identical, which the golden-record criterion above enforces. The one real hazard is the `newunit=` switch in step 3 interacting with the still-hardcoded unit 1 elsewhere in `src/samplers.f90`; if step 3 is deferred to a follow-up, verify that a `startmode=2` run (which reaches `load_starting_points` via `sample`, `src/samplers.f90:13,77,81`) still reads `start.dat` correctly.
