### ISSUE TITLE
Add better RK than RK4/5: DOPRI5 or RKN

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#57]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

Still open and still relevant. Line references below are against SIMPLE `d8b0e01` and libneo `fe3f76e`; re-resolve them if either has moved.

Nothing named DOPRI/Dormand-Prince/Nyström exists anywhere in SIMPLE or libneo history — `git log --oneline --all -i --grep='dopri\|dormand\|nystrom'` and `git log --all -S'dopri' --oneline` both return empty in both repositories (verified). The issue body is empty, so this comment supplies the spec.

## Purpose

Every non-symplectic integration in SIMPLE goes through one routine: libneo's `odeint_allroutines`, an adaptive Cash-Karp RK5(4) whose tableau is hard-coded as module parameters at `libneo/src/odeint/odeint_allroutines.f90:26-64`. That single routine backs:

| Call site | Purpose |
|---|---|
| `src/orbit_symplectic_quasi.f90:548` | `integmode = 0` guiding-centre trace |
| `src/sub_alpha_lifetime_can.f90:198`, `:214`, `:408`, `:410` | non-canonical / near-axis trace |
| `src/field/field_can_meiss.f90:528` | Meiss canonical construction |
| `src/get_canonical_coordinates.F90:202` | legacy canonical-flux construction |
| `src/spectre_orbit.f90:282` | SPECTRE per-volume guiding-centre trace |

The RK45 path is the reference against which the symplectic integrators are validated, which makes its cost and its event-location accuracy load-bearing well beyond `integmode = 0`.

Cash-Karp RK5(4) (Cash & Karp 1990) was designed for problems with rapidly varying right-hand sides, not for minimal error constants. Dormand-Prince 5(4) is the better default at equal RHS cost: both spend 6 derivative evaluations per accepted step (DOPRI5 has 7 stages but is first-same-as-last), DOPRI5 has smaller leading error coefficients, and it carries a free order-4 dense-output polynomial. The dense output is the physically important part here — SIMPLE locates Poincaré cuts, wall crossings, and SPECTRE interface crossings by root-finding *inside* an accepted step, and the current code does that with a cubic Hermite interpolant, i.e. dense output of order 3 in the Hairer/Nørsett/Wanner sense (`libneo/src/odeint/odeint_allroutines.f90:515-533`, called from `find_event_in_step` at `:660` and `:685`).

## Current state

**The tableau.** Hard-coded Cash-Karp coefficients as module parameters:

```fortran
    ! Cash-Karp Butcher tableau coefficients (standard notation)
    ! Nodes (c vector)
    real(dp), parameter :: c2 = 0.2_dp
    ...
    real(dp), parameter :: a21 = 0.2_dp
    ...
    ! Error weights (b* - b)
    real(dp), parameter :: e1 = b1 - 2825.0_dp/27648.0_dp
```
(`libneo/src/odeint/odeint_allroutines.f90:26-64`)

The stages are computed by `compute_all_stages_fused` (`:824-883`) and `compute_all_stages_fused_context` (`:886-946`) with `h*a_ij` manually unrolled — there is no tableau-driven loop, so a second method cannot be added by swapping coefficient arrays. `compute_rk_step` (`:748`) and `compute_rk_step_context` (`:758`) are the only entry points into the stage code. The work array is `k_stages(:,:)`, allocated in `allocate_state` (`:87-106`) and indexed `k_stages(stage, component)` — note that `k_stages(1, :)` is therefore a *strided* slice, not contiguous.

**Step control.** Classic Numerical-Recipes elementary controller, no PI term, no memory of the previous error:

```fortran
        if (error_max > 1.0_dp) then
            step_accepted = .false.
            h_temp = safety_factor*h*pow_m025(error_max)
            h = sign(max(abs(h_temp), 0.1_dp*abs(h)), h)
            ...
        else
            ...
            if (error_max > error_constant) then
                h_next = safety_factor*h*pow_m02(error_max)
            else
                h_next = 5.0_dp*h
            end if
```
(`libneo/src/odeint/odeint_allroutines.f90:786-820`)

Error norm is an L-infinity max over `|y_error(i)/y_scale(i)|` (`compute_error_norm`, `:769-783`) with `y_scale(i) = |y(i)| + |h*k1(i)| + tiny_value` (`compute_error_scale_fused`, `:438-451`, assignment at `:448`) — a pure relative measure with no separate `atol`, so a component passing through zero is scaled only by `|h*k1|`.

**No FSAL, plus a redundant call.** Each step calls `derivative` once for `k1` (`:294`; context variant `:393`) and, when events are active, a *seventh* call for `f_end` (`:308`). Two separate wins are available here:

1. DOPRI5's last stage *is* `f` at the step endpoint, so with FSAL both the next `k1` and `f_end` are free.
2. Even without changing the method, the `f_end` call at `:308` is redundant whenever no event fires: `y_end = y_work` at `:307`, `x` has already been advanced, and if `find_event_in_step` returns `event_found = .false.` the loop falls through to `h = h_next` (`:329`) and re-enters at `:294` calling `derivative(x, y_work, k_stages(1, :))` with the identical `x` and `y_work`. Confirm this against `:306-330` before relying on it.

**Callers throw away the adaptive step.** The `integmode = 0` guiding-centre driver restarts the integrator on every macro-step:

```fortran
subroutine orbit_timestep_rk45(ierr)
  use odeint_allroutines_sub, only : odeint_allroutines
  ...
  do while(ktau .lt. si%ntau)
    call odeint_allroutines(si%z, 4, ktau*si%dt, (ktau+1)*si%dt, si%rtol, f_ode)
    ktau = ktau+1
  end do
end subroutine orbit_timestep_rk45
```
(`src/orbit_symplectic_quasi.f90:539-551`, call at `:548`)

`odeint_allroutines_no_context` sets `h_init = x2 - x1` when `initial_stepsize` is absent (`libneo/.../odeint_allroutines.f90:198`; context variant `:224`), so with the default `relerr = 1d-13` (`src/params.f90:83`) every macro-step begins with a step size that is essentially guaranteed to be rejected, burns several rejections re-deriving the same `h`, and then discards it. `src/sub_alpha_lifetime_can.f90:195-214` does the same per `dtaumin`. Any "better RK" is worth much less until that restart is fixed, so it belongs in this issue. The optional `initial_stepsize` argument already exists (`:193`); only a way to read back the final `h` is missing.

**Selection surface.** `integmode` is an integer with `RK45 = 0` (`src/orbit_symplectic_base.f90:20`), dispatched in `orbit_sympl_init` (`src/orbit_symplectic.f90:200-263`, `case (RK45)` at `:226`) and documented in `DOC/coordinates-and-fields.md:931` and `:1019`.

## Reproduction / evidence

This is a quality/performance request, so here is a verification recipe rather than a bug repro. `wout.nc` is **not** checked in — it is downloaded on demand (see `test/test_data/get_test_data.sh` and `test/golden_record/run_golden_tests.sh:56-60`), so fetch it first:

```bash
# 0. fetch the VMEC fixture the golden-record cases use
mkdir -p /tmp/integ_data
wget -q https://github.com/hiddenSymmetries/simsopt/raw/master/tests/test_files/wout_LandremanPaul2021_QA_reactorScale_lowres_reference.nc \
     -O /tmp/integ_data/wout.nc

# 1. build (CLAUDE.md: CMake via make, never fpm, never raw ctest)
make CONFIG=Fast

# 2. cost of the current RK45 path vs the symplectic ones on one case
tools/integrator_bench/bench_integrators.sh ./build/simple.x \
    /tmp/integ_data/wout.nc test/golden_record/boozer/simple.in /tmp/integ_bench
```

`tools/integrator_bench/bench_integrators.sh:16-17` maps `integmode 0 -> RK45` and the script prints `rc`, `conf_frac`, `newton_maxit`, and `wall_s` per mode; record the `integmode 0` row. Then the accuracy probe, which needs no new fixture:

```bash
make CONFIG=Fast test TEST=test_orbit_refcoords_rk45
```

`test/tests/magfie/test_orbit_refcoords_rk45.f90:38-43` traces `n_steps = 100` at `dtaumin = 1.0e-3`, `relerr = 1.0e-10` and checks `tol_mu_conservation = 1.0e-3`. That test is the natural place to add a work-vs-precision comparison: for a fixed number of RHS evaluations, DOPRI5 must give a magnetic-moment drift no worse than Cash-Karp.

Numbers to measure rather than assume:
- RHS evaluations per unit `tau` at `relerr = 1d-13`. FSAL removes 1 of 7 calls (~14%) on *accepted* steps only; rejected steps still waste the last stage. Smaller DOPRI5 error constants should buy larger accepted steps on top of that. Report the measured figure; do not assume it.
- Event/cut location improves from order-3 Hermite to order-4 dense output at zero extra RHS cost — verify by measuring empirical convergence order, not by asserting a fixed factor.
- Golden records stay bit-identical, because the new method is opt-in and the default stays Cash-Karp.

## Behaviour (BDD)

```gherkin
Scenario: Cash-Karp remains the default and golden records do not move
  Given libneo gains a DOPRI5 method but SIMPLE sets no new namelist key
  When I run "make CONFIG=Fast test-regression"
  Then every case under test/golden_record/ (albert, albert_coils, boozer,
       boozer_ncsx, canonical, classifier, classifier_combined, classifier_fast,
       collision, meiss, meiss_coils, test_tokamak, test_tokamak_classifier)
       compares bit-identical to its reference via
       test/golden_record/compare_golden_results.sh

Scenario: DOPRI5 is selectable and reproduces a known orbit
  Given a scratch copy of test/golden_record/boozer/simple.in (ntestpart = 32)
        with "ode_method = 'dopri5'" added to &config and integmode left at its
        default of 0
  When I run "./build/simple.x simple.in" in that directory with wout.nc present
  Then the final confined fraction in confined_fraction.dat agrees with the
       ode_method='cashkarp' run to within 1/ntestpart = 0.03125
  And the run uses strictly fewer RHS evaluations than the cashkarp run

Scenario: DOPRI5 converges at the documented order on an analytic problem
  Given harmonic_rhs from libneo test/odeint/odeint_test_common.f90
  When I integrate over one period at fixed h, for h halved four times
  Then the global error of the 5th-order solution decreases by a factor
       between 25 and 40 per halving (empirical order 5.0 +/- 0.3)
  And the embedded error estimate decreases by a factor between 12 and 20
       (empirical order 4.0 +/- 0.3)

Scenario: Dense output is order 4 where Hermite is order 3
  Given an event in libneo test/odeint/test_odeint_events.f90 whose exact root
        is known analytically
  When I locate that root at fixed step sizes h, h/2, h/4, h/8, once with
       hermite_interpolate and once with the DOPRI5 dense-output interpolant
  Then the empirical convergence order of |x_event - x_exact| is 3.0 +/- 0.5
       for Hermite and 4.0 +/- 0.5 for dense output
  And at the smallest h the dense-output error is strictly smaller

Scenario: Adaptive step size survives the SIMPLE macro-step loop
  Given orbit_timestep_rk45 in src/orbit_symplectic_quasi.f90 carrying h across
        ktau instead of restarting from h = si%dt
  When a particle is traced for si%ntau macro-steps at relerr = 1d-13
  Then the number of rejected steps per macro-step is <= 1 after the first
       macro-step
```

## Implementation plan

Almost all of this lands in **libneo**, which owns the integrator; SIMPLE only gains a selector.

**Cross-repo mechanics — read before step 14.** SIMPLE does **not** pin `LIBNEO_REF` in `Makefile`. `cmake/Util.cmake:76-100` uses `-DLIBNEO_REF=<ref>` if passed on the command line and otherwise calls `get_branch_or_main` (`cmake/Util.cmake:3`), which fetches the libneo branch with the same name as the current SIMPLE branch, falling back to `main`. So: use the *same branch name* in both repos to get cross-repo CI, and land the libneo PR on `main` before merging the SIMPLE PR. The only pinned ref is `GOLDEN_LIBNEO_REF := e451e0a4...` in `Makefile:4`, used by `test-regression` (`Makefile:77`); it was last set by `2390095` ("Align golden dependency FP contract (#453)") and must **not** be touched.

**Note on RKN.** Descope Runge-Kutta-Nyström. RKN integrates `y'' = f(x, y)` with a right-hand side independent of `y'`. None of SIMPLE's systems has that form: the guiding-centre system in canonical coordinates is first-order (`f_ode`, `src/orbit_symplectic_quasi.f90:517-534`), and the full-orbit Lorentz force in `src/orbit_fo_boris.f90` depends on velocity through `v x B`. Explicit symplectic RKN would additionally require a separable Hamiltonian `H = T(p) + V(q)`, which the guiding-centre Hamiltonian is not — that non-separability is precisely why SIMPLE uses implicit symplectic schemes (Albert, Kasilov & Kernbichler 2020). Record this in the PR description rather than silently dropping it.

1. **`libneo/src/odeint/rk_tableau.f90` (new).** Define `type :: rk_tableau_t` with `integer :: stages`, `logical :: fsal`, `real(dp), allocatable :: a(:,:), b(:), bhat(:), c(:)`, `integer :: order, order_hat`, and optional dense-output coefficients `real(dp), allocatable :: d(:)`. Provide `cashkarp_tableau()` and `dopri5_tableau()` constructors. Cash-Karp coefficients move here verbatim from `odeint_allroutines.f90:26-64`; DOPRI5 coefficients from Dormand & Prince (1980), dense-output `d` vector from Shampine (1986). Cross-check both against `scipy.integrate.RK45` (`scipy/integrate/_ivp/rk.py`, class `RK45`), which uses the same tableau and the same order-4 interpolant.
2. **`libneo/src/odeint/odeint_allroutines.f90` (edit).** Generalise `compute_all_stages_fused` (`:824-883`) and `compute_all_stages_fused_context` (`:886-946`) into a tableau-driven stage loop over `1..tableau%stages`, keeping the existing `k_stages(stage, component)` index order but sizing the first extent `tableau%stages` in `allocate_state` (`:87-106`; note the existing size check is on `size(k_stages, 2)`). Keep the unrolled Cash-Karp path as a specialisation if the benchmark in step 9 shows a regression; otherwise delete it. Add `fsal` handling: when `tableau%fsal`, reuse the last stage as the next step's `k1` instead of calling `derivative` at `:294` / `:393`.
3. **`libneo/src/odeint/odeint_allroutines.f90` (edit).** Add module-level method state and a public `subroutine odeint_set_method(name)` accepting `'cashkarp'` (default) and `'dopri5'`. It must be declared `!$omp threadprivate` alongside `odeint_failed` (`:134-135`) — SIMPLE traces one particle per OpenMP thread (`trace_parallel`, `src/simple_main.f90:583-639`). Do **not** change the argument order or names of `odeint_allroutines_no_context` / `odeint_allroutines_context`.
4. **`libneo/src/odeint/odeint_allroutines.f90` (edit).** Add `dense_output(tableau, y0, k_stages, h, s, y_out)` and call it from `find_event_in_step` (`:556-686`) in place of `hermite_interpolate` at `:660` and `:685` when the active tableau has dense coefficients; fall back to `hermite_interpolate` (`:515-533`) when it does not, so Cash-Karp event results do not move.
5. **`libneo/src/odeint/odeint_allroutines.f90` (edit).** Add an optional PI step controller for DOPRI5: `h_new = h * min(facmax, max(facmin, safety * err**(-1/(p+1)) * err_prev**beta))` with `beta = 0.04`, `facmax = 5`, `facmin = 0.2`, as in Hairer/Nørsett/Wanner II.4. Keep the existing elementary controller (`adjust_step_size`, `:786-820`) for `'cashkarp'` so the golden record does not move. Also add an optional `atol` argument, defaulting to the current pure-relative behaviour, giving `y_scale = atol + rtol*(|y| + |h*k1|)`; the current `y_scale` at `:448` has no absolute floor.
6. **`libneo/src/odeint/odeint_allroutines.f90` (edit, optional but cheap).** Skip the redundant `f_end` evaluation at `:308` by reusing the previous step's endpoint derivative when no event fired (see "No FSAL, plus a redundant call" above). This helps Cash-Karp too, so if it changes any result it must be gated behind the method switch.
7. **`libneo/test/odeint/test_odeint_dopri5.f90` (new)** and **`libneo/test/odeint/CMakeLists.txt` (edit).** Register with the existing pattern (`add_executable` / `target_link_libraries ... odeint_test_common` / `add_test`). Cover: order-5 convergence on `harmonic_rhs` from `test/odeint/odeint_test_common.f90`, order-4 convergence of the embedded estimate, dense-output accuracy against the analytic solution at interior points, and thread safety mirroring `test/odeint/test_odeint_thread_safety.f90`.
8. **`libneo/test/odeint/test_golden_record_odeint.f90` (edit).** Add an assertion that with no `odeint_set_method` call the results still match the tagged golden implementation to the existing `tol = epsilon(1.0_dp)*200` (`:13`). This is the guard that the refactor is behaviour-preserving.
9. **`SIMPLE/src/params.f90` (edit).** Add `character(len=16) :: ode_method = 'cashkarp'` and append it to the `namelist /config/` list at `:164-187`. Validate it in `params_init` next to the existing `canonical_ode_relerr` check (`:227-230`), erroring on anything but `'cashkarp'` / `'dopri5'`.
10. **`SIMPLE/src/simple_main.f90` (edit).** Call `odeint_set_method(ode_method)` once per thread inside the parallel region in `trace_parallel` (`:583-639`), not in serial init — the method flag is threadprivate.
11. **`SIMPLE/src/orbit_symplectic_quasi.f90` (edit).** Add a saved, threadprivate `real(dp) :: rk_h_carry`, initialise it in `orbit_sympl_init`, and pass it as `initial_stepsize` to the `odeint_allroutines` call at `:548`, updating it from the last accepted `h`. This requires libneo to return the final `h`: add an optional `real(dp), intent(out) :: h_final` to both `odeint_allroutines_*` (purely additive, so existing positional callers are unaffected).
12. **`SIMPLE/src/sub_alpha_lifetime_can.f90` (edit).** Same step-carry treatment for the `dtaumin` loop at `:195-214`.
13. **`SIMPLE/test/tests/CMakeLists.txt` (edit)** and **`SIMPLE/test/tests/test_ode_method.f90` (new).** Follow the `test_orbit_frequencies` pattern at `test/tests/CMakeLists.txt:353-358`: trace the same particle with `ode_method='cashkarp'` and `'dopri5'` at `relerr = 1d-11`, assert the final `(s, th, ph, p_phi)` agree to `1d-8` relative, and assert DOPRI5 uses fewer RHS calls (count via a module counter in the test's own RHS wrapper). Set `LABELS "physics"` and `TIMEOUT 120`.
14. **`SIMPLE/DOC/coordinates-and-fields.md` (edit).** Update the `integmode` rows at `:931` and `:1019`, and document `ode_method` next to them.
15. **Cross-repo landing.** Per the mechanics note above: matching branch names in both repos during review, libneo merged to `main` first, `GOLDEN_LIBNEO_REF` untouched. No `LIBNEO_REF` edit is needed or possible in `Makefile`.

**Ordering:** libneo PR (steps 1-8) -> merge -> SIMPLE PR (steps 9-15).

## Acceptance criteria

- [ ] `make CONFIG=Fast test-regression` passes with every `test/golden_record/` case bit-identical (default path unchanged).
- [ ] `make CONFIG=Fast test` and `make CONFIG=Fast test-smoke` pass in SIMPLE against the updated libneo.
- [ ] libneo `odeint` tests pass, including the new `test_odeint_dopri5` and the unchanged `test_golden_record_odeint` at `tol = epsilon(1.0_dp)*200`.
- [ ] Measured empirical convergence order on `harmonic_rhs` is `5.0 +/- 0.3` for the DOPRI5 solution and `4.0 +/- 0.3` for the embedded estimate.
- [ ] Measured empirical convergence order of event-location error is `4.0 +/- 0.5` for dense output versus `3.0 +/- 0.5` for `hermite_interpolate`.
- [ ] `test_ode_method` passes: cashkarp vs dopri5 final state agree to `1d-8` relative at `relerr = 1d-11`, and the dopri5 RHS-call count is strictly lower.
- [ ] `tools/integrator_bench/bench_integrators.sh` `integmode 0` on `test/golden_record/boozer/simple.in`: with `ode_method='dopri5'` plus step-carry the wall time is **not higher** than the `cashkarp` baseline and the confined fraction is unchanged to within `1/ntestpart = 0.03125`. Record the measured wall-time and RHS-count deltas in the PR description. (A 15% gain is the hope, not a merge gate: FSAL alone caps out near 14% and only on accepted steps.)
- [ ] `test_orbit_refcoords_rk45` still passes with `tol_mu_conservation = 1.0e-3` under both methods.
- [ ] `DOC/coordinates-and-fields.md` documents `ode_method`.
- [ ] PR carries the required `tier/*` and `size/*` labels and a filled `.github/pull_request_template.md` per `docs/review-policy.md`.

## References

- J. R. Dormand and P. J. Prince, *A family of embedded Runge-Kutta formulae*, J. Comput. Appl. Math. **6** (1980) 19-26 — the DOPRI5(4) tableau.
- P. J. Prince and J. R. Dormand, *High order embedded Runge-Kutta formulae*, J. Comput. Appl. Math. **7** (1981) 67-75 — the RK8(7) family behind DOP853, if a higher-order option is wanted later.
- L. F. Shampine, *Some practical Runge-Kutta formulas*, Math. Comp. **46** (1986) 135-150 — the order-4 dense-output interpolant for DOPRI5.
- E. Hairer, S. P. Nørsett, G. Wanner, *Solving Ordinary Differential Equations I: Nonstiff Problems*, 2nd ed., Springer 1993 — II.4 (step-size control incl. PI), II.6 (dense output), II.14 (Nyström methods). Reference implementations `dopri5.f` / `dop853.f`.
- J. R. Cash and A. H. Karp, *A variable order Runge-Kutta method for initial value problems with rapidly varying right-hand sides*, ACM TOMS **16** (1990) 201-222 — what the code implements today.
- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, J. Comput. Phys. **403** (2020) 109065 (arXiv:1903.06885) — SIMPLE's own method paper; source of the non-separability argument that rules out explicit symplectic RKN.
- `scipy.integrate.RK45` (`scipy/integrate/_ivp/rk.py`) — an independent implementation of the same tableau and dense output, useful for validating the coefficient tables in step 1.

## Scope and risk

Two PRs, libneo before SIMPLE; the libneo one is the larger (tableau extraction plus a controller plus dense output).

- **Performance regression on the default path.** `compute_all_stages_fused` is deliberately hand-unrolled and SIMD-annotated; generalising it to a tableau loop may cost Cash-Karp performance. Step 9's benchmark is a gate, not a nicety, and keeping the unrolled specialisation is an acceptable outcome.
- **Thread safety.** The method flag and any carried step size must be `threadprivate` like `odeint_failed` (`libneo/src/odeint/odeint_allroutines.f90:134-135`), or `trace_parallel` will produce nondeterministic results and break the golden records.
- **Shared dependency.** libneo's `odeint_allroutines` is used by codes other than SIMPLE. Every change must be opt-in and default-identical.

**Related issues (cross-links only — contents not verified in this pass):** itpplasma/libneo#298, itpplasma/libneo#103, itpplasma/SIMPLE#303. Check #298 first: if it moves `odeint_allroutines` onto a different backend, steps 1-6 should follow it there rather than creating a second integrator in libneo.

**Suggested split:** three atomic issues — (a) libneo: tableau-driven stages + DOPRI5 + dense output + PI controller, opt-in; (b) SIMPLE: `ode_method` namelist key and threadprivate wiring; (c) SIMPLE: carry the adaptive step size across macro-steps in `orbit_timestep_rk45` and the `sub_alpha_lifetime_can` loop. Item (c) is independently valuable and can land first.
