### ISSUE TITLE
Implement field line tracing

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#58]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

The issue body is empty, so this triage reconstructs the intent from the code and then specifies it. Verdict: **still relevant, refine**. Field-line tracing exists in SIMPLE today in exactly two forms, neither of which is a usable field-line-tracing capability for SIMPLE's own field stack: an internal RK sampler helper that throws its trajectory away, and a SPECTRE-only symplectic tracer that cannot see VMEC, Boozer, Meiss, Albert or chartmap fields.

## Purpose

Field-line tracing is the cheapest direct diagnostic of a 3D equilibrium: Poincaré sections show islands and stochastic layers, and the field-line rotational transform validates the coordinate/field evaluation stack independently of any orbit integrator. Today every such check in SIMPLE goes through guiding-center orbits, which convolve field errors with integrator errors. A field-line tracer over `field_can_t` isolates the field: in the canonical gauge the field line is a one-degree-of-freedom Hamiltonian flow with `phi` as time, `theta` as coordinate and `A_theta` as momentum, and its rotational transform must reproduce the VMEC `iota` profile. It also gives SIMPLE the island/stochasticity diagnostic that its optimization-facing issues (#351 smooth Poincaré-map proxy, #39 SIMSOPT loss optimization) currently have to source elsewhere.

## Current state

**1. There is an RK field-line integrator, but it is private plumbing for particle sampling.**
`integrate_mfl_can` (`src/sub_alpha_lifetime_can.f90:271-336`) integrates a field line over `phi` through the global `magfie` pointer and accumulates flux-tube volume for volumetric sampling. Its RHS is `rhs_mflint_can` (`src/sub_alpha_lifetime_can.f90:228-267`):

```fortran
dery(1)=hctrvr(1)/hctrvr(3)
dery(2)=hctrvr(2)/hctrvr(3)
dery(3)=1.d0/(bmod*hctrvr(3))
dery(4)=bmod/hctrvr(3)
dery(5)=bmod**2/hctrvr(3)
```

Its only caller is `init_starting_surf` (`src/samplers.f90:23-52`), which keeps `xstart`, `bstart`, `volstart` for `sample_surface_fieldline_impl` (`src/samplers.f90:261-288`) and discards the trajectory itself. There is no output file, no Poincaré section, no iota, no CLI. `test_poincare1.x` is built at `test/tests/CMakeLists.txt:388-389` but **never registered with `add_test`** (verified: `test_poincare1` appears only on those two lines of that file) — it is dead weight, not coverage.

Note a real defect in the same routine: `src/sub_alpha_lifetime_can.f90:285` declares

```fortran
integer, intent(in) :: npoi, ierr
```

while `call chamb_can(y(1:2),phi,ierr)` (lines 300 and 319) passes `ierr` to a dummy that `chamb_can` defines (`src/chamb_m.f90:9-30`: `integer :: ierr`, documented as an output, assigned unconditionally). Passing an `intent(in)` dummy as the actual argument of a defined dummy is a standards violation that current compilers happen to tolerate; fix it in the same PR.

**2. There is a proper symplectic field-line tracer, but only for SPECTRE.**
`src/field_line_spectre.f90` (added in `9fd7d6c`, "Add symplectic field-line Poincare app for SPECTRE equilibria (#437)"; upgraded to implicit midpoint in `fc20806`, "Use implicit midpoint for SPECTRE field lines (#483)" — both verified ancestors of `origin/main`) implements the canonical formulation, documented in its own header (`src/field_line_spectre.f90:1-14`):

```
dtheta/dzeta = -dA_zeta/ds / dA_theta/ds
dpsi/dzeta   =  dA_zeta/dtheta - dA_theta/dtheta * dA_zeta/ds/dA_theta/ds
```

with `field_line_step` (`src/field_line_spectre.f90:102-133`) driving a Newton solve on the midpoint residual (`solve_midpoint`/`midpoint_residual`/`midpoint_jacobian`, `src/field_line_spectre.f90:135-207`). Every hot-loop procedure that touches the equilibrium is hard-typed to `type(spectre_data_t)` (`spectre_reader`, from libneo `src/spectre/spectre_reader.f90`) and to `spectre_vecpot_t` (libneo `src/spectre/spectre_basis.f90:13-20`, components `Ath, Azt, dAth(3), dAzt(3), d2Ath(6), d2Azt(6)`). The app `app/spectre_poincare.f90` (registered at `CMakeLists.txt:522-533`) wraps it. Consequently `test_field_line_midpoint` (`test/tests/CMakeLists.txt:865-872`) and `test_spectre_poincare` (`test/tests/CMakeLists.txt:854-863`) cover SPECTRE only — both are driven by the libneo fixture `test/spectre/data/spectre_test.h5`.

**3. `field_can_t` already carries what the formulation needs, but with caveats.** `field_can_t` (`src/field/field_can_base.f90:12-34`) exposes `Ath, Aph, dAth(3), dAph(3)` for every canonical family, and `field_can_mod::evaluate` (`src/field_can.f90:25`) is the dispatching pointer set by `field_can_from_name` (`src/field_can.f90:33+`) for `test`, `flux`, `boozer`, `meiss`, `albert`, `spectre`. The canonical gauge `A_r = 0` is built into the type (there is no `Ar` component), which is exactly the condition that makes `(theta, A_theta)` a canonical pair with `phi` as time. The same ratio already appears at `src/magfie_can_boozer.f90:169`:

```fortran
aiota = -dA_phi_dr/dA_theta_dr
```

so `dtheta/dphi` from the tracer must equal `aiota` — a built-in consistency check.

Two caveats that shape the design and the tests, both verified in source:

- **Second derivatives are not usable for an analytic Jacobian.** `mode_secders = 1` yields second derivatives *only* in `d/dr^2`; mixed and angular second derivatives need `mode_secders = 2` (`src/field/field_can_boozer.f90:82-84`). More importantly `f%d2Ath` is set to zero and never filled for boozer (`src/field/field_can_boozer.f90:106`), albert (`src/field/field_can_albert.f90:72`) and flux (`src/field/field_can_flux.f90:67`); only meiss fills it (`src/field/field_can_meiss.f90:833`). **Keep the finite-difference Jacobian that `midpoint_jacobian` already uses.** (The claim that SPECTRE lacks second derivatives is also false — `spectre_vecpot_t` carries `d2Ath`/`d2Azt`.)
- **In `flux` and `boozer` the angular derivatives of the vector potential are identically zero** — `f%dAth = 0d0; f%dAph = 0d0` followed by filling only `dAth(1)`/`dAph(1)` (`src/field/field_can_boozer.f90:102-113`). That is the defining property of straight-field-line coordinates, and it means `dpsi/dphi = 0`: `r` is constant and the section is a circle *by construction*. So the boozer/flux iota check is a strong end-to-end test of the **field evaluation stack** but does **not** exercise the implicit solver, and it cannot show islands. Nontrivial sections require `meiss`, `albert` or `spectre`. Say this in the PR description so nobody reads a clean boozer section as evidence of anything about the equilibrium.

For `flux` and `boozer` the integrator radial coordinate *is* VMEC `s` (`integ_to_ref_boozer`, `src/field/field_can_boozer.f90:43-53`, and `integ_to_ref_flux`, `src/field/field_can_flux.f90:24-33`, both set `xref(1) = xinteg(1)`), so comparison against `spline_vmec_sub::splint_iota` (libneo `src/vmec_support/spline_vmec_data.f90:1214-1244`) is direct, with no radial remapping.

## Reproduction / evidence

There is nothing to reproduce; this is a capability gap. Verification recipe for the new feature, using fixtures that already exist. The field setup is read from an ordinary `simple.in` through `params::read_config` — exactly the pattern of `app/simple_diag_orbit.f90:53-68` — and only the tracing parameters live in the new namelist, so no field-setup keys are duplicated.

```bash
# wout.nc is auto-downloaded by CMake to test/test_data/wout.nc
# (test/tests/CMakeLists.txt:14-28; LandremanPaul2021 QA reactor-scale, lowres)
make CONFIG=Fast
cd build && cp ../test/test_data/wout.nc .

cat > simple.in <<'EOF'
&config
  netcdffile = 'wout.nc'
  ns_s = 5
  ns_tp = 5
  multharm = 5
  integ_coords = 2
  ntestpart = 1
  sbeg = 0.5d0
/
EOF

cat > field_line.in <<'EOF'
&fieldline
  s_seeds = 0.1d0, 0.3d0, 0.5d0, 0.7d0, 0.9d0
  theta_seed = 0.2d0
  phi0 = 0.0d0
  nturns = 500
  nsteps_per_period = 256
/
EOF

./field_line.x simple.in field_line.in
```

`integ_coords` is the field selector (`src/params.f90:144`, `src/params.f90:612-617`; `isw_field_type` is its deprecated alias). Confirm the numeric value for `boozer` against `field_can_mod::field_can_from_id`/`name_from_id` (`src/field_can.f90:121,144`) before writing the fixture — do not guess it.

Expected: `poincare.dat` with 5 x 500 section points and `iota.dat` with one fitted rotational transform per seed. Because the flow is `dpsi/dphi = 0` in Boozer coordinates, each section must be a circle at constant `s`, and the fitted iota must agree with `splint_iota` at the seed `s`.

Baseline for cross-checking: libneo's independent cylindrical RK tracer `neo_poincare::make_poincare` (`libneo/src/poincare.f90:46-70`, tested in `libneo/test/poincare/test_poincare.f90`). It takes `class(field_t)` from `neo_field_base` (`libneo/src/poincare.f90:3,48`), not SIMPLE's `field_can_t`, so it cannot be reused directly; it is a reference implementation, not a drop-in.

## Behaviour (BDD)

```gherkin
Scenario: Rotational transform reproduces the VMEC iota profile in Boozer coordinates
  Given build/wout.nc (test/test_data/wout.nc, LandremanPaul2021 QA lowres)
  And simple.in selecting the boozer canonical field with ns_s=5, ns_tp=5, multharm=5
  And field_line.in with s_seeds = 0.1, 0.3, 0.5, 0.7, 0.9,
      nturns = 500, nsteps_per_period = 256
  When ./field_line.x simple.in field_line.in is run from build/
  Then iota.dat contains one row per seed with columns (s_seed, iota_fit)
  And each iota_fit agrees in sign and magnitude with
      spline_vmec_sub::splint_iota(s_seed) to relative tolerance 1e-9
  And the traced s stays within 1e-12 of s_seed for every section point,
      because dAth(2:3) and dAph(2:3) are identically zero in boozer

Scenario: The analytic circular tokamak reproduces its closed-form transform
  Given the 'test' canonical field (src/field/field_can_test.f90:23-51,
      B0 = 1, iota0 = 1, a = 0.5, R0 = 1), which needs no wout.nc
  And a seed at r = 0.2, theta = 0.0, phi = 0.0
  When 200 toroidal turns are traced with nsteps_per_period = 512
  Then the fitted transform equals iota0*(1 - r**2/a**2) = 0.84 exactly
      to relative tolerance 1e-3
  # Derivation: dAph(2)=dAph(3)=0 so r is constant, and
  #   dtheta/dphi = -dAph(1)/dAth(1) = iota0*(r-r**3/a**2)/(r-r**2*cos(theta)/R0).
  # Integrating dphi over one poloidal turn gives 2*pi/(iota0*(1-r**2/a**2)).

Scenario: The field-line Hamiltonian is conserved on the analytic tokamak
  Given the same 'test' seed and trace
  When A_phi is evaluated at every section point
  Then max |A_phi(state_k) - A_phi(state_0)| < 1e-12
  # A_phi is the conserved quantity: H = -A_phi and the test field is
  # phi-independent (dAth(3)=dAph(3)=dhth(3)=0), so H is autonomous.
  # A_theta (= pth) is NOT conserved in general - it is the evolving momentum.
  And the radial coordinate r stays within 1e-13 of 0.2

Scenario: The midpoint map is time-reversible for every canonical field family
  Given field_can_from_name('flux'|'boozer'|'meiss'|'albert') initialized on wout.nc
  When field_line_step is applied with step h and then with -h from the same state
  Then max |(r, theta, phi, pth)_final - (r, theta, phi, pth)_initial| < 2e-11
      (same criterion and form as test/tests/test_field_line_midpoint.f90:23-25)

Scenario: Step-halving converges at second order on a non-trivial field
  Given field_type meiss on wout.nc at s = 0.5, nturns = 100
  When nsteps_per_period is 64, 128 and 256
  Then the section-point error against the 1024-step run falls by a factor
      between 3.5 and 4.5 per halving
  # meiss, not boozer: in boozer the map is an exact constant-rate rotation
  # at any step size, so no convergence order can be measured there.
```

## Implementation plan

1. **Create `src/field_line.f90`** — new module `field_line_mod`, generic over `field_can_t`. Public: `field_line_state_t` (components `r, theta, phi, pth`), `field_line_init(state, r, theta, phi)` setting `pth = f%Ath` from one `field_can_mod::evaluate` call, `field_line_step(state, h)`, and `field_line_iota(state, h, nturns)` returning the fitted transform. Port the residual/Jacobian/Newton structure of `src/field_line_spectre.f90:135-207` verbatim, substituting `call evaluate(f, r, th, ph, 0)` from `field_can_mod` for `eval_spectre_vector_potential`, and `f%Aph, f%dAph` for `av%Azt, av%dAzt`. Reuse the existing constants `max_newton = 20`, `newton_tol = 1.0e-13_dp`, `fd_scale = epsilon(1.0_dp)**(1.0_dp/3.0_dp)` (`src/field_line_spectre.f90:28-30`). **Keep the central-difference Jacobian** — see the `d2Ath` caveat above; do not attempt an analytic Jacobian in this PR.
2. **Do not touch `src/field_line_spectre.f90`.** SPECTRE has its own vector-potential type and its own volume/radius-recovery logic (`recover_radius`, `src/field_line_spectre.f90:209-230`); unifying them is a separate, later refactor. Note the duplication in a `!>` comment in the new module and cross-reference it.
3. **Create `app/field_line.f90`** — program `field_line_main`. Model the field setup on `app/simple_diag_orbit.f90:52-68`: `call read_config(config_file)` then `call init_field(norb, netcdffile, ns_s, ns_tp, multharm, integmode)`. **Do not also call `field_can_from_name`** — `simple_main::init_field` (`src/simple_main.f90:282-420`) already calls `init_field_can(isw_field_type, ...)` at `src/simple_main.f90:409` and `:415`, and the field family is selected by `integ_coords` in the `&config` namelist. Take `argv(1)` as the `simple.in` path (default `simple.in`) and `argv(2)` as the `&fieldline` namelist path (default `field_line.in`), and follow `app/spectre_poincare.f90:78-90` for the missing-file handling. Write `poincare.dat` (columns: seed index, turn index, r, theta, R, Z) and `iota.dat` (columns: seed s, fitted iota). For `R`, `Z`, use `reference_coordinates::ref_coords%evaluate_cart` — the same route `src/netcdf_results_output.f90:433-476` uses for particle positions, which returns **Cartesian** `(x, y, z)`; take `R = hypot(x, y)`, `Z = z`. It requires `init_reference_coordinates` to have run, which `init_field` handles; guard with the same `allocated(ref_coords)` check as `src/netcdf_results_output.f90:451-455`.
4. **Wire the app in `CMakeLists.txt`** — add an `add_executable(field_line.x app/field_line.f90)` block immediately after the `spectre_poincare.x` block at `CMakeLists.txt:522-533`, copying its `target_compile_options(... ${SIMPLE_COMPILE_OPTIONS})`, the GNU `-Wtrampolines`/`-Werror=trampolines` guard, `target_link_libraries(... PRIVATE simple)` and `RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}`. Add `field_line.f90` to the `simple` library source list in `src/CMakeLists.txt`, next to `field_line_spectre.f90` at `src/CMakeLists.txt:27`.
5. **Create `test/tests/test_field_line_canonical.f90`** — Fortran unit test covering the reversibility scenario for `flux`, `boozer`, `meiss`, `albert` on `wout.nc`, plus the two `test`-field scenarios (closed-form transform 0.84 and `A_phi` conservation), which need no fixture at all. Register in `test/tests/CMakeLists.txt` next to the `test_field_line_midpoint` block at lines 865-872, with `LABELS "unit"` and a `TIMEOUT` in line with neighbouring VMEC tests.
6. **Create `test/tests/test_field_line_iota.py`** — Python test running `field_line.x`, reading `iota.dat`, and comparing against `iota` from `test/test_data/wout.nc` read with `netCDF4` and interpolated with `scipy`. Register with `add_test` following the `test_spectre_poincare` pattern at `test/tests/CMakeLists.txt:854-863` (same `${BOOZER_CHARTMAP_PYTHON}` interpreter variable, `LABELS "integration;python"`). Put the step-halving convergence check here too, on `meiss`.
7. **Fix `src/sub_alpha_lifetime_can.f90:285`**: `integer, intent(in) :: npoi, ierr` becomes `integer, intent(in) :: npoi` plus `integer, intent(out) :: ierr`. Verify `init_starting_surf` still reports "starting field line has points outside the chamber" (`src/samplers.f90:42-45`) correctly.
8. **Document in `DOC/coordinates-and-fields.md`** — the canonical field-line formulation, the sign convention (`iota = -dA_phi/dr / dA_theta/dr`, matching `src/magfie_can_boozer.f90:169`), the namelist keys, the output file columns, and the boozer/flux triviality caveat. This is required by repo policy: `CLAUDE.md:72` states that any change to coordinate- or field-related code MUST revise `DOC/coordinates-and-fields.md`.

No libneo change is required: `field_can_t` and `splint_iota` are already available. If a cylindrical-coordinate Poincaré mode is wanted later, that belongs in `libneo/src/poincare.f90` and should be a separate issue.

## Acceptance criteria

- [ ] `make CONFIG=Fast` builds `build/field_line.x` with no new warnings (`Fast` is a supported build type, `CMakeLists.txt:65`).
- [ ] `make test TEST=field_line` passes, running both `test_field_line_canonical` and `test_field_line_iota`, and still running the pre-existing `test_field_line_midpoint`.
- [ ] Fitted iota matches `splint_iota` in sign and magnitude to relative `1e-9` at `s = 0.1, 0.3, 0.5, 0.7, 0.9` on `test/test_data/wout.nc`, for the `boozer` and `flux` families.
- [ ] Traced `s` deviates from the seed by less than `1e-12` over 500 turns in `boozer`.
- [ ] On the `test` field at `r = 0.2`, the fitted transform matches the closed form `iota0*(1 - r**2/a**2) = 0.84` to relative `1e-3`, and `max |A_phi - A_phi(0)| < 1e-12`.
- [ ] Reversibility residual `< 2e-11` for `flux`, `boozer`, `meiss`, `albert`.
- [ ] Section-point error under step-halving on `meiss` falls by a factor in `[3.5, 4.5]` (second order).
- [ ] `make test-golden-fast` (`Makefile:105-106`) shows no change in any golden record — the new module must be additive and must not alter `init_starting_surf` behaviour beyond the `intent` fix.

Optional, and fine to split into its own issue if it inflates the diff: register `test_poincare1.x` with `add_test` or delete it. A built-but-never-run executable (`test/tests/CMakeLists.txt:388-389`) is not coverage.

## References

- Hairer, Lubich & Wanner, *Geometric Numerical Integration*, 2nd ed. (Springer, 2006) — implicit midpoint as a symplectic, time-reversible, second-order map; the source of the convergence-order and reversibility criteria above.
- Meiss, *Symplectic maps, variational principles, and transport*, Rev. Mod. Phys. **64**, 795 (1992) — island widths and stochasticity thresholds from the field-line map, i.e. what the Poincaré output is for.
- Hazeltine & Meiss, *Plasma Confinement* (Addison-Wesley, 1992) — the magnetic field-line Hamiltonian and the `A_theta`-as-momentum construction. (Standard textbook treatment; chapter not verified here.)
- Hudson et al., *Computation of multi-region relaxed magnetohydrodynamic equilibria*, Phys. Plasmas **19**, 112502 (2012) — the SPEC paper. Per issue #437, `src/field_line_spectre.f90` follows the SPOIC/SPECTRE per-volume tracer rather than SPEC's own code directly.
- Comparable implementations: **SIMSOPT** (`simsopt.field.tracing.compute_fieldlines`) and **BEAMS3D** trace field lines in cylindrical coordinates with adaptive RK, which is the approach of `libneo/src/poincare.f90`. Cross-code numerical claims beyond "they trace in cylindrical coordinates" were not verified for this triage; do not cite them as benchmarks without checking.

## Scope and risk

Single PR, roughly `size/M`: one new module (~250 lines ported from a proven one), one new app, two new tests, one `intent` fix, one doc section. Risk is low because the feature is purely additive — the only shared code touched is the `intent(in)`/`intent(out)` correction in `integrate_mfl_can`, which is compile-time-checkable and covered by the existing golden records.

Two design traps:

- **Sign convention.** `src/field_line_spectre.f90:12-14` warns explicitly that flipping either update sign reverses iota, so the `splint_iota` comparison must be signed, not on absolute values. The `test`-field closed form gives `+0.84` with the sign convention of `src/magfie_can_boozer.f90:169`; use it as the orientation anchor.
- **Do not oversell the boozer result.** As established above, `dpsi/dphi = 0` identically in `flux` and `boozer`, so nested circular sections there are a property of the coordinates, not a finding about the equilibrium.

Related issues (all verified open in the issue set): **#437** (the SPECTRE-only tracer this generalizes; its app now exists on `main` as `app/spectre_poincare.f90`); **#33** ("Starting field line is not computed for multiple flux surfaces" — the same `init_starting_surf`/`integrate_mfl_can` code path, worth fixing in coordination); **#351** ("Explore smooth Poincare-map proxy for alpha-loss optimization", a downstream consumer of this output); **#39** (SIMSOPT loss-optimization context).
