### ISSUE TITLE
Add reverse tracing from the wall

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#59]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

The issue body is empty, so this comment reconstructs the request from the title and from what the wall machinery actually does today. Nothing resembling reverse tracing exists on `main`: `rg -n -i 'reverse|backward|time_reversal' src/ app/ test/` returns only unrelated hits (spline direction in `src/field/psi_transform.f90`, mirror reflection in `src/interface_crossing.f90:220`, field-line orientation in `src/field_line_spectre.f90:13`, sort-order tests in `test/tests/test_sorting.f90`, a "time went backwards" clock check in `test/tests/test_timing.f90`), and `git log --oneline --all -S'reverse_trace'` is empty. Still relevant — spec below.

## Purpose

SIMPLE computes wall footprints by forward-tracing markers from a flux surface and intersecting each accepted microstep with an STL wall (`src/simple_main.f90:1806` `locate_wall_segment`, `src/wall/stl_wall_intersection.F90`). Forward tracing answers "where do markers born at `sbeg` land"; it does not answer the inverse question a wall-load or divertor-design study needs: *which part of the plasma and which part of velocity space feeds this particular wall tile*. With forward sampling, resolving one hot tile requires the whole marker population to be scaled up until enough markers happen to land there. Backward-in-time tracing from the wall inverts the sampling: launch on the tile, integrate with a negative time step, and record where the orbit came from.

A reverse mode is also a direct consistency check on the wall/boundary event locator: a correctly located wall event must reproduce the forward trajectory when replayed backwards. That makes it useful against the RK45-vs-symplectic footprint discrepancy in itpplasma/SIMPLE#303.

The guiding-centre system integrated here is autonomous, so backward tracing is *not* a new physics model: it is the same vector field integrated with `dt < 0`. No flip of `v_par` and no charge flip is needed. Flipping `v_par` alone is *wrong*, because the grad-B drift depends on `mu` (i.e. `v_perp**2`) and the curvature drift on `v_par**2` — both are even in `v_par`, so negating `v_par` reverses the parallel streaming but leaves the drift pointing the same way.

## Current state (verified at `d8b0e01`)

The time step reaches the integrators as a strictly positive `dtaumin`. It is computed in two branches of `params_init` (`src/params.f90:261-366`) — the TEST-field branch at `src/params.f90:281-283` and the general branch at `src/params.f90:303-305`, both of the form:

```fortran
dtaumin = 2.d0*pi*rbig/npoiper2
ntau = ceiling(dtau/dtaumin)
dtaumin = dtau/ntau
```

and is handed to every pusher unconditionally (`src/simple_main.f90:1173-1175`):

```fortran
            call init_fo(anorb%fo, z, dtaumin)
        else if (integmode > 0) then
            call init_sympl(anorb%si, anorb%f, z, dtaumin, dtaumin, relerr, integmode)
```

with two further `init_sympl` call sites at `src/simple_main.f90:683` (GPU comparison path) and `src/simple_main.f90:1039` (classifier path). `init_sympl` (`src/simple.f90:123-154`) forwards `dtaumin/dsqrt(2d0)` into `orbit_sympl_init`, which stores it verbatim as `si%dt` (`src/orbit_symplectic.f90:214`).

Note the guard inside `init_sympl` (`src/simple.f90:134-137`): it `error stop`s unless `mod(dtau, dtaumin)` is within `1d-9*dtaumin` of 0 or of `dtaumin`, and it passes `nint(dtau/dtaumin)` as the macrostep count `ntau`. **Both** arguments must carry the same sign — signing only one yields a negative `ntau`.

Time bookkeeping multiplies microstep counters by `dtaumin` at `src/simple_main.f90:1231,1238,1249,1278,1282` (and again in the SPECTRE and classifier paths at 1324, 1357, 1370, 1374, 1460, 1489, 1498), so a negative `dtaumin` leaking into these lines would silently produce negative `times_lost`.

Three ingredients are already reverse-friendly and should not be rewritten:

- the RK45 path bottoms out in libneo `odeint_allroutines`, which sets `h_init = sign(initial_stepsize, x2 - x1)` in both the no-context and context interfaces (`libneo/src/odeint/odeint_allroutines.f90:199-202` and `:225-228`) — backward integration already works there;
- the Boris pusher `fo_step` (`src/orbit_fo_boris.f90:444-471`) is the standard drift-kick-drift form (half-drift, exact rotation, half-drift) and is exactly time-reversible under `dt -> -dt`;
- `MIDPOINT` and `GAUSS1..GAUSS4` are symmetric collocation methods, so `Phi_{-h}` is the exact inverse of `Phi_{h}` up to Newton tolerance. `EXPL_IMPL_EULER` is *not* self-adjoint (its adjoint is `IMPL_EXPL_EULER`), so a round trip in `integmode=1` closes only to `O(dt)`. This must be documented, not "fixed".

What is missing:

- **A direction switch.** There is no direction key anywhere in the `&config` namelist (`src/params.f90:164-187`).
- **Sign-safe time accounting.** See the `dtaumin/v0` sites above.
- **An inward stop condition.** The symplectic domain guards are one-sided against `sympl_rmax` (declared `src/orbit_symplectic_base.f90:17`, default `1.0d0`). `rg -n 'sympl_rmax' src/orbit_symplectic.f90` returns roughly 20 comparison sites, in several distinct syntactic forms — scalar `radius > sympl_rmax` (`:195`), `x(1) > sympl_rmax` (`:560,581,628,1220,1601,1670,1905,1913`), `x(1) > sympl_rmax .or. x(5) > sympl_rmax` (`:798`), `any(x(radial_indices) > sympl_rmax)` (`:825,944,1286`), `x(radius_index) > sympl_rmax` (`:1228`), stage loops `x(4*ks-3) > sympl_rmax` (`:918,1011`), and `any(x(1:4*s:4) > sympl_rmax)` (`:2081`). Any mirrored guard must cover all of them, not a subset.
- **A way to start markers at the wall.** `sample_particles` (`src/simple_main.f90:840-874`) has startmodes 1-5 only. `stl_wall_intersection.F90` exports only `stl_wall_t`, `stl_wall_init`, `stl_wall_finalize`, `stl_wall_first_hit_segment`, `stl_wall_first_hit_segment_with_normal` (lines 9-13); the C++ side (`src/wall/stl_wall_cgal.cpp`) exposes only `stl_wall_create`, `stl_wall_destroy`, and the two first-hit entry points (lines 125, 171, 179, 234). There is no triangle enumeration.

The Cartesian-to-reference inverse that wall sampling needs **already exists** and should be reused rather than rewritten. `ref_coords` (`reference_coordinates`, `src/coordinates/reference_coordinates.f90`) is used forward as `evaluate_cart(u_ref, x_cart)` in `src/simple_main.f90:1164,1933,1980,2016,2062`, and the type-bound inverse is `from_cart(x, u, ierr)` (`src/coordinates/scaled_chartmap_coordinates.f90:107-117`, delegating to `chartmap_coordinate_system_t%from_cart`). `src/orbit_fo_boris.f90:73-115` wraps it as `invert_cart_warm`/`invert_warm_newton`: a damped Newton from a warm seed with a robust multi-seed `from_cart` fallback on stall. Note that `integ_to_ref` is **not** this map — it converts *integration* coordinates to reference coordinates and is unrelated to the Cartesian inverse.

## Reproduction / evidence

There is no bug to reproduce; this is a feature. Verification recipe, self-contained: the `test_tokamak` fixture uses `isw_field_type = -1`, the analytic circular tokamak, so no `wout.nc` download is needed. Its full contents (`test/golden_record/test_tokamak/simple.in`) are:

```
&config
multharm = 3             ! Not used for TEST field but set for consistency
contr_pp = -1e10         ! Trace all passing particles
trace_time = 1d-4        ! slowing down time, s
sbeg = 0.3d0             ! starting s for particles
ntestpart = 32           ! number of test particles
isw_field_type = -1      ! TEST: analytic circular tokamak (no input files needed)
deterministic = .True.   ! reproducible random walk
/
```

It sets neither `integmode` nor `relerr`; both must be added for the round-trip check.

```bash
make CONFIG=Fast                       # CONFIG=Fast is a valid build type, CMakeLists.txt:65
mkdir -p /tmp/revtest && cd /tmp/revtest
cp <repo>/test/golden_record/test_tokamak/simple.in .
sed -i 's/ntestpart = 32/ntestpart = 8/' simple.in
sed -i 's|^/$|integmode = 3\nrelerr = 1d-13\noutput_results_netcdf = .True.\n/|' simple.in
<repo>/build/simple.x                  # forward run
```

Then take `zend` from `results.nc` (components documented at `src/netcdf_results_output.f90:203-205`: `s (flux), theta (rad), zeta (rad), p (v/v0), v_par/v`), write it to `start.dat`, and rerun with `startmode = 2` plus the new `trace_direction = -1`. Expected: `zend` of the reverse run equals `zstart` of the forward run to `<= 1e-10` in all five components for every non-lost marker. Observed today: impossible to express — the namelist has no direction key (`src/params.f90:164-187`).

Once wall sampling exists, the wall-side check is: forward-run a chartmap case with `wall_input` set, take the `wall_hit_cart`/`zend` of a lost marker, replay it backwards, and confirm the reverse endpoint lands within `1e-8` of the forward `zstart`.

## Behaviour (BDD)

```gherkin
Scenario: symmetric integrator round trip closes to Newton tolerance
  Given test/golden_record/test_tokamak/simple.in edited to integmode = 3, ntestpart = 8, relerr = 1d-13
  And a forward run whose results.nc zend has been written to start.dat
  When simple.x runs with startmode = 2 and trace_direction = -1
  Then results.nc:zend of the reverse run equals the forward results.nc:zstart
   And the componentwise absolute difference is below 1d-10 for s, theta, zeta, p, v_par/v

Scenario: non-symmetric integrator is only first-order reversible
  Given the same case with integmode = 1 (EXPL_IMPL_EULER)
  When the forward-then-reverse round trip is run
  Then the closure error is O(dtaumin), not machine precision
   And stdout carries the warning "trace_direction=-1 with integmode=1 is not self-adjoint"

Scenario: an unsigned direction key is rejected
  Given simple.in with trace_direction = 0
  When simple.x starts
  Then it stops with "trace_direction must be +1 or -1"

Scenario: reported times stay positive under reverse tracing
  Given any run with trace_direction = -1
  When write_output writes times_lost.dat
  Then every finite entry is >= 0 and equals elapsed |t| in seconds

Scenario: collisions are rejected in reverse mode
  Given simple.in with swcoll = .True. and trace_direction = -1
  When simple.x starts
  Then it stops with "trace_direction=-1 is incompatible with swcoll"

Scenario: defaults reproduce d8b0e01 exactly
  Given simple.in with neither trace_direction nor reverse_stop_s set
  When make test-golden runs
  Then every case under test/golden_record/ reports zero diffs

Scenario: markers launched on the wall stop at the target surface
  Given a chartmap case with wall_input set, startmode = 6 and reverse_stop_s = 0.2
  When simple.x runs with trace_direction = -1 and ntestpart = 64
  Then every marker either records orbit_exit_code = ORBIT_EXIT_REVERSE_TARGET with zend(1) within 1d-6 of 0.2
   Or reaches trace_time and is reported unresolved
```

## Implementation plan

Split into two PRs; PR1 is independently useful and testable. Do not start PR2 until PR1 has merged.

**PR1 — negative-time integration (no wall dependency).**

1. `src/params.f90`: add `integer :: trace_direction = 1` next to `startmode` (line 57) and `real(dp) :: reverse_stop_s = -1d0`. Add both to the `&config` namelist (the list spans lines 164-187; append before the closing `restart`). At the end of `read_config` (`src/params.f90:197-236`, after the `read (1, nml=config)` at line 201), `error stop 'trace_direction must be +1 or -1'` unless `trace_direction == 1 .or. trace_direction == -1`.
2. `src/params.f90`, inside `params_init` (lines 261-366): after `dtaumin` is finalised in *both* branches (lines 283 and 305), introduce a module-level `real(dp) :: dtau_signed` set to `trace_direction*dtaumin`. Keep `dtaumin` strictly positive so every `kt*dtaumin/v0` expression stays an elapsed magnitude.
3. `src/simple_main.f90`: pass `dtau_signed` to the pushers. At line 1173 use `call init_fo(anorb%fo, z, dtau_signed)`. At lines 683, 1039 and 1175 use `call init_sympl(..., z, dtau_signed, dtau_signed, relerr, integmode)` — **both** the `dtau` and `dtaumin` arguments, because `src/simple.f90:152` computes `nint(dtau/dtaumin)` and a mixed sign would make `ntau` negative. Also sign the RK45 calls `orbit_timestep_axis(z, dtaumin, dtaumin, ...)` at lines 1679, 1682 **and 1743**, and the SPECTRE call `orbit_timestep_spectre(state, z, dtaumin, ...)` at line 1320. Leave lines 1231, 1238, 1249, 1278, 1282 (and 1324, 1357, 1370, 1374, 1460, 1489, 1498) on `dtaumin` so reported times stay positive.
4. `src/simple_main.f90`, `validate_orbit_model_config` (defined at lines 267-280, called from line 143): add `if (trace_direction == -1 .and. swcoll) error stop 'trace_direction=-1 is incompatible with swcoll'` — the pitch-angle/energy Monte-Carlo operator in `src/collis_alphas.f90` is a stochastic process and is not reversible. Add a printed warning when `trace_direction == -1 .and. (integmode == 1 .or. integmode == 2)`.
5. `src/orbit_symplectic_base.f90`: add `real(dp) :: sympl_rmin = -1d0` beside `sympl_rmax` (line 17), and add it to the `use` list at `src/orbit_symplectic.f90:9`. In `src/orbit_symplectic.f90`, mirror **every** `sympl_rmax` comparison listed under "Current state" above with the corresponding `< sympl_rmin` test setting `SYMPLECTIC_STEP_OUTSIDE_DOMAIN`. Re-run `rg -n 'sympl_rmax' src/orbit_symplectic.f90` after editing and confirm each comparison site has a mirror; the pure-threshold sites (`:258,743,816,935,1277,1889,1968`, of the form `sympl_rmax > 1d0`) are feature switches, not guards, and need no mirror. Default `-1d0` keeps current behaviour bit-for-bit because `s >= 0` always.
6. `src/params.f90`: add `integer, parameter :: ORBIT_EXIT_REVERSE_TARGET = 4` to the exit-code block at lines 45-53 (0/1/2/3 and 101-105 are taken). In `src/simple_main.f90`, extend `classify_orbit_exit` (defined at lines 1064-1113) to return it, and in the tracing loop set `sympl_rmin = reverse_stop_s` when `trace_direction == -1 .and. reverse_stop_s > 0` so the inward stop is not misreported as a numerical fault. Note that `physical_exit` at `src/simple_main.f90:1227-1229` currently tests only `ORBIT_EXIT_LCFS`/`ORBIT_EXIT_WALL` — add the new code there too, or reverse hits will be counted as faults.
7. `src/netcdf_results_output.f90`: write `trace_direction` and `reverse_stop_s` as global attributes next to `startmode` (line 334), and add them to the `use params, only:` list at line 52.
8. New test `test/tests/orbit/test_reverse_tracing.f90`: for `integmode = 3, 4, 5`, initialise a tracer on the TEST field (`isw_field_type = -1`), advance `N` microsteps forward, re-init with `-dtaumin`, advance `N` back, assert `maxval(abs(z - z0)) < 1e-10`; assert the `integmode = 1` round-trip error scales like `dtaumin` (halve `dtaumin`, expect the error to roughly halve). Register it in `test/tests/CMakeLists.txt` following the four-line pattern at lines 623-626 (`add_executable` / `target_link_libraries(... simple testing_utils)` / `add_test` / `set_tests_properties(... LABELS "unit;orbit")`) — but place it *outside* any `if(SIMPLE_ENABLE_CGAL)` block, unlike the block those lines sit in.
9. `DOC/config.md` and `simple.in`: document `trace_direction` and `reverse_stop_s`, including the self-adjointness caveat for `integmode = 1, 2`.

**PR2 — launching from the wall (depends on PR1).**

10. `src/wall/stl_wall_cgal.cpp`: add `extern "C" int stl_wall_num_triangles(void* h)` and `extern "C" int stl_wall_get_triangle(void* h, int i, double v0[3], double v1[3], double v2[3], double normal[3])`, following the existing entry points at lines 125-260. Bind them in `src/wall/stl_wall_intersection.F90` and add them to the `public` list at lines 9-13. Both must be inside the `#ifdef SIMPLE_ENABLE_CGAL` block.
11. `src/samplers.f90`: add `sample_wall_surface(zstart)` — draw a triangle with probability proportional to area, draw a barycentric point, then map that Cartesian point to reference coordinates with the **existing** inverse `ref_coords%from_cart(x, u, ierr)` (`src/coordinates/scaled_chartmap_coordinates.f90:107`). There is no warm seed available at sampling time, so call `from_cart` directly rather than the warm-start wrapper `invert_cart_warm` (`src/orbit_fo_boris.f90:73-98`), and skip-and-redraw any point where `ierr /= 0`, capping retries. Then draw the pitch from the inward hemisphere weighted by `|cos|` so the reverse population is the adjoint of an isotropic flux onto the tile. Reuse the deterministic seed path `reset_seed_if_deterministic` (defined in `src/params.f90:621-632`, **not** in `samplers.f90`). Remember `stl_wall` vertices are in metres while `from_cart` expects the chartmap Cartesian scale — divide by `chartmap_cart_scale_to_m`, inverting the multiplication at `src/simple_main.f90:1165`. That variable is a `save`d module-scope variable inside `simple_main` (set from `meta%cart_scale_to_m`), so it is not visible from `samplers.f90`: pass it in as an argument rather than adding a `use` cycle.
12. Add a unit test that round-trips `evaluate_cart` against `from_cart` to `1e-10` for a sample of near-wall points, so a sampler failure is distinguishable from an inverse-map failure.
13. `src/simple_main.f90:840-874`: add an `elseif (6 == startmode) then / call sample_wall_surface(zstart)` branch before the `else` error arm, and `error stop` if `wall_enabled` is false (`wall_enabled` is a saved module variable declared at line 52 and set true at line 529).
14. New test `test/python/test_reverse_wall_roundtrip.py`: forward-run a chartmap wall case, extract a lost marker's `zend`, write `start.dat`, reverse-run with `startmode = 2, trace_direction = -1`, assert the reverse endpoint matches the forward `zstart` to `1e-8`. Register it in `test/python/CMakeLists.txt` following the `add_test(NAME test_simple_api_${test_name} ...)` pattern at lines 18 and 31.

No libneo change is required: `odeint_allroutines` already honours a negative interval.

## Acceptance criteria

- [ ] `make CONFIG=Fast` builds clean.
- [ ] `make test TEST=test_reverse_tracing` passes; round-trip error `< 1e-10` for `integmode = 3, 4, 5`, and the `integmode = 1` error halves when `dtaumin` halves.
- [ ] `rg -n 'sympl_rmax' src/orbit_symplectic.f90` — every *comparison* site (not the `sympl_rmax > 1d0` feature switches) has a matching `sympl_rmin` mirror.
- [ ] `make test-golden` shows zero diffs for all cases in `test/golden_record/` — with `trace_direction = 1` and `reverse_stop_s = -1d0` defaults the run must be bit-identical to `d8b0e01`.
- [ ] `simple.in` with `swcoll = .True.` and `trace_direction = -1` exits non-zero with the documented message; `trace_direction = 0` likewise.
- [ ] `times_lost.dat` contains no negative finite entries in a reverse run, and `confined_fraction.dat` is monotone as before.
- [ ] `results.nc` carries `trace_direction` and `reverse_stop_s` global attributes.
- [ ] PR2 only: `make test TEST=test_stl_wall_intersection` still passes with `-DSIMPLE_ENABLE_CGAL=ON`.
- [ ] PR2 only: the `evaluate_cart`/`from_cart` round-trip unit test passes to `1e-10`.
- [ ] PR2 only: reverse endpoint of a replayed wall hit matches the forward start within `1e-8`.

## References

- C. G. Albert, S. V. Kasilov, W. Kernbichler, *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement fusion*, J. Comput. Phys. **403** (2020) 109065 — the integrator family this repo implements.
- E. Hairer, C. Lubich, G. Wanner, *Geometric Numerical Integration*, 2nd ed., Springer (2006), §II.3 (The Adjoint of a Method) and Ch. V (Symmetric Integration and Reversibility) — symmetric methods satisfy `Phi_{-h} = Phi_h^{-1}`, while the explicit and implicit Euler variants are mutual adjoints. This is the correctness argument for step 5 and for the `integmode = 1` caveat.
- J. R. Cary, A. J. Brizard, *Hamiltonian theory of guiding-center motion*, Rev. Mod. Phys. **81**, 693 (2009) — guiding-centre equations; the drift terms depend on `mu` and `v_par**2` and are therefore even in `v_par`, which is why "flip `v_par` and keep `dt > 0`" is not a valid time reversal.
- H. Qin, S. Zhang, J. Xiao, J. Liu, Y. Sun, W. M. Tang, *Why is Boris algorithm so good?*, Phys. Plasmas **20**, 084503 (2013) — volume preservation and time-reversibility of the drift-kick-drift Boris map used in `src/orbit_fo_boris.f90`.
- E. E. Lewis, W. F. Miller, *Computational Methods of Neutron Transport*, Wiley (1984) — adjoint/backward Monte Carlo as a variance-reduction technique for rare-detector problems; the same argument motivates launching from a wall tile rather than from the core.
- J. Varje et al., *High-performance orbit-following code ASCOT5 for Monte Carlo simulations in fusion plasmas*, arXiv:1908.02482 (2019) — the closest comparable orbit-following code, cited for context on 3D wall-load workflows. This triage pass did not verify whether ASCOT5 supports backward tracing, so no capability comparison is claimed here.

The one-sided `sympl_rmax` guard, the `dtaumin` sign convention, and the coordinate-inversion plumbing are implementation details internal to this code; no literature reference applies.

## Scope and risk

Two PRs. PR1 is roughly `size/M` and low risk: both new knobs default to current behaviour and the golden records gate that. The real hazard is applying the sign to the *reporting* path as well as the *integration* path, which would flip `times_lost` and silently corrupt `confined_fraction.dat` — hence the explicit split between `dtau_signed` and `dtaumin` in steps 2-3. The second hazard is signing only one of the two `init_sympl` step arguments, which makes `ntau` negative (`src/simple.f90:153`); step 3 spells this out.

PR2 is roughly `size/M`. Its risk sits in two places: the CGAL C++ layer, which is only built when `SIMPLE_ENABLE_CGAL=ON` and so needs its own CI check; and the `from_cart` inversion, which can fail to converge for wall points that sit outside or exactly on the chartmap boundary — the sampler must treat a non-zero `ierr` as skip-and-redraw, never as a silent zero.

Related open issues, none of which subsume this one: itpplasma/SIMPLE#303 (RK45 refcoords misses a footprint cluster — a reverse replay of the symplectic footprint would localise where the RK45 path diverges), itpplasma/SIMPLE#415 (FLR dressing at wall checks) and itpplasma/SIMPLE#416 (adaptive GC-to-full-orbit near the wall) — both change what a wall hit *is*, so they should land before PR2's sampler is tuned.
