### ISSUE TITLE
Add fields from SIMSOPT

### ISSUE THREAD

**Issue by krystophny** [itpplasma/SIMPLE#60]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `d8b0e01`. Verify before acting.*

This issue has an empty body and dates from 2024-09-12, days after `748be8a` "Non-flux coordinates (#56)" (2024-09-07) and `5de27cd` "Coils running" (2024-09-04) landed the first field abstraction. I checked whether the intent has since been satisfied. It has not, so this is a refine rather than a close — but the scope needs to be pinned down, because "fields from SIMSOPT" now means exactly one concrete gap.

**What SIMSOPT artifacts SIMPLE already consumes:** VMEC `wout` NetCDF written by `simsopt.mhd.Vmec` works today and is the primary test fixture source — `test/tests/CMakeLists.txt:18`, `test/python/CMakeLists.txt:4`, `test/conftest.py:22`, `README.md:229` and `CLAUDE.md:120` all pull `wout_LandremanPaul2021_*_reactorScale_lowres_reference.nc` from `hiddenSymmetries/simsopt`, and `test/tests/CMakeLists.txt:232` pulls `wout_c09r00_fixedBoundary_0.5T_vacuum_ns201.nc` from the same source. Plasma *boundaries* in SIMSOPT JSON are also handled: `tools/quasr_json_to_boundary.py` reads `obj["simsopt_objs"]` and unpacks a `SurfaceXYZTensorFourier` into a GVEC boundary NetCDF. Note that this tool is currently unreferenced by any test, CMake target or Makefile rule — `grep -rn quasr_json_to_boundary` matches only the file itself — so it is a pattern to copy, not a tested pattern.

**What is missing:** the vacuum/coil field. SIMPLE's only coil path is `field_input = 'coils.simple'` (`src/field.F90:132-137` → `create_coils_field`, `src/field/field_coils.f90:43`), which reads libneo's bespoke flat point-list format (`libneo/src/field/biotsavart.f90:40-54`). The only converter in tree targets the STELLOPT/MAKEGRID text format (`test/tests/convert_coils_stellopt_to_simple.py`, mirrored in Fortran at `test/tests/convert_coils_stellopt_to_simple.f90`, wired at `test/tests/CMakeLists.txt:258-281`). There is no reader for a SIMSOPT-serialized coil set, which is the format QUASR distributes and the format any SIMSOPT coil-optimization run produces. `git log --all --grep=simsopt -i` finds only `draft/compare_simsopt.py` work on unmerged branches (`1a5afd1` "Add more comparisons to simsopt", `7878586`, `dbd4434`) — `git merge-base --is-ancestor 1a5afd1 origin/main` returns false, and no `draft/` directory exists on `main`.

---

## Purpose

Coil-derived vacuum fields are the input SIMPLE needs whenever losses must be evaluated against a *buildable* device rather than an idealized fixed-boundary equilibrium — coil-ripple losses, finite-coil-count degradation of quasisymmetry, and free-boundary edge structure are all invisible to a `wout`-only workflow. SIMSOPT is the framework the group already benchmarks against and the source of every VMEC fixture in the test suite; QUASR publishes coil sets in SIMSOPT JSON, and `tools/quasr_json_to_boundary.py` plus `Makefile:19` (`SIMPLE_FIGURE8_DATA_ROOT ?= $(HOME)/data/QUASR/SIMPLE/figure8`) show the group is already pulling from it. Closing this gap means a QUASR or SIMSOPT-optimized configuration can go from JSON to a confined fraction without a manual detour through MAKEGRID.

## Current state

`field_from_file` (`src/field.F90:69-142`) dispatches on filename. The coil branch is the last one, at lines 132-137:

```fortran
        else if (startswidth(stripped_name, 'coils') .or. &
                 endswith(filename, '.coils')) then
            call create_coils_field(filename, raw_coils)
            allocate (splined_coils)
            call create_splined_field(raw_coils, ref_coords, splined_coils)
            call move_alloc(splined_coils, field)
```

`create_coils_field` (`src/field/field_coils.f90:43-59`) delegates the parse to libneo and then converts units (lines 48-56):

```fortran
        real(dp), parameter :: M_TO_CM = 100.0d0
        real(dp), parameter :: A_TO_STATA = 2997924536.8431d0

        call load_coils_from_file(coils_file, field%coils)

        field%coils%x = field%coils%x * M_TO_CM
```

So the on-disk contract is **SI: metres and amperes**, and everything inside `coils_field_t` is CGS (cm, statamperes, Gauss).

The libneo reader is a flat list (`libneo/src/field/biotsavart.f90:40-54`): first line `n_points`, then `n_points` rows of `x y z current`. Critically, `current(i)` is the current of the *segment from point i to point i+1* — `compute_magnetic_field` (`libneo/src/field/biotsavart.f90:113-134`) loops `i = 1, size(coils%x) - 1` and uses `coils%current(i)` for the segment between points `i` and `i+1`; `compute_vector_potential` (lines 91-110) does the same, and the `!> Formula of Hanson and Hirshman (2002)` comment sits at line 90. Multiple filaments are therefore separated by the MAKEGRID convention: repeat each coil's first point at its end and give that row `current = 0`, so the segment joining one coil to the next contributes nothing. `test/tests/convert_coils_stellopt_to_simple.py` preserves that fourth column verbatim (its parse loop, lines 19-35), which is why the STELLOPT path works.

The evaluator signature you will assert against is `coils_evaluate` (`src/field/field_coils.f90:21-40`):

```fortran
subroutine coils_evaluate(self, x, Acov, hcov, Bmod, sqgBctr)
    class(coils_field_t), intent(in) :: self
    real(dp), intent(in) :: x(3)
    real(dp), intent(out) :: Acov(3), hcov(3), Bmod
    real(dp), intent(out), optional :: sqgBctr(3)
```

`x` is in **cm** and `Bmod` comes out in **Gauss**.

Consumers of `coils.simple` today: golden records `test/golden_record/albert_coils/simple.in` (`isw_field_type = 4`) and `test/golden_record/meiss_coils/simple.in` (`isw_field_type = 3`), both with `field_input = 'coils.simple'`; the Fortran executables `test/tests/magfie/test_magfie_coils.f90` and `test/tests/magfie/test_coils_field_compare.f90` (built in `test/tests/magfie/CMakeLists.txt:1-5` — note these two are built but not registered with `add_test`); and the Python helper `python/pysimple/coil_clearance.py:27` (`load_coil_points`), which parses the same point-file format.

The existing SIMSOPT-JSON reader to copy is `tools/quasr_json_to_boundary.py:13-17`:

```python
def find_surface(obj):
    for key, value in obj["simsopt_objs"].items():
        if key.startswith("SurfaceXYZTensorFourier"):
            return value
    raise ValueError("No SurfaceXYZTensorFourier object found")
```

and the `dofs` indirection at lines 32-33:

```python
    dofs_ref = surface["dofs"]["value"]
    dofs = np.array(simsopt_objs[dofs_ref]["x"]["data"], dtype=float)
```

**Schema caveat.** That is the *only* knowledge of the SIMSOPT serialization format present in this repository, and it covers surfaces, not coils. There is no `.json` fixture anywhere in the tree (`find . -name '*.json' -not -path './.git/*'` returns only `.devcontainer/`, `.vscode/` files). The coil-side schema (`Coil`, `CurveXYZFourier`, `Current`, `RotatedCurve` and their `dofs` links) therefore **cannot be derived from this checkout** and must not be hand-invented. Step 3 below says how to obtain it honestly.

## Reproduction / evidence

The gap is demonstrable in one command. Take any SIMSOPT-serialized coil set (a QUASR device JSON, or the output of `simsopt.save([...])` on a list of `Coil` objects) and point SIMPLE at it:

```bash
cd /path/to/SIMPLE
make CONFIG=Fast
cp test/golden_record/albert_coils/simple.in .
sed -i "s|field_input = 'coils.simple'|field_input = 'quasr_device.json'|" simple.in
./build/simple.x simple.in
```

Observed: `field_from_file` falls through every branch — the name neither starts with `coils` nor ends in `.coils` or `.nc`, and `is_spectre_file` (`src/field.F90:144-175`) returns false because the HDF5 magic check fails on JSON — so it hits `src/field.F90:139`:

```fortran
            print *, 'field_from_file: Unknown file name format ', filename
            error stop
```

Expected after this issue: the JSON is recognized and the user is told exactly how to convert it (see step 2 — Fortran gains no JSON parser).

### Analytic verification recipe

The converter output is verifiable without SIMSOPT installed. A closed polyline is a **regular polygon**, not a circle, and the Hanson–Hirshman straight-segment formula is exact for it — so assert against the polygon value, and use the circle only as a sanity bound. For a regular `N`-gon of circumradius `a` carrying current `I`, the field at the centre is exactly

```
B = mu0 * I * N * tan(pi/N) / (2*pi*a)
```

which tends to the circular-loop `mu0*I/(2a)` as `N -> inf`. For `a = 1 m`, `I = 1e6 A`, in Gauss:

| N | exact polygon (G) | circle (G) | rel. difference |
|---|---|---|---|
| 128 | 6284.447260 | 6283.185307 | 2.0085e-4 |
| 256 | 6283.500738 | 6283.185307 | 5.0202e-5 |
| 512 | 6283.264161 | 6283.185307 | 1.2550e-5 |
| 1024 | 6283.205021 | 6283.185307 | 3.1375e-6 |

**This corrects a tempting mistake: at `N = 512` the polygon differs from the circle by `1.255e-5`, so a `1e-5` tolerance against the circular-loop formula would fail.** Use `1e-10` against the polygon value and `5e-5` against the circle.

For the axial field of a regular `N`-gon of circumradius `a` at axial distance `d`, with apothem `r = a*cos(pi/N)`, side `L = 2*a*sin(pi/N)`, `rho2 = r*r + d*d`:

```
B_z = mu0 * I * N * r * L / (4*pi * rho2 * sqrt(rho2 + L*L/4))
```

For two such coils at `z = -0.5 m` and `z = +0.5 m`, `a = 1 m`, `I = 1e6 A`, evaluated at the origin, `N = 512`: `B = 8991.807994 G` (the two-circular-loop limit `2*mu0*I*a^2/(2*(a^2+d^2)^1.5)` gives `8991.762856 G`, a `5.020e-6` difference).

## Behaviour (BDD)

```gherkin
Scenario: Point-file writer emits the libneo flat format with a zero-current separator
  Given a request for one closed circular filament of radius 1.0 m,
        centre [0,0,0], normal +z, current 1.0e6 A, with 512 segments
  When I run "python3 tools/simsopt_json_to_coils.py --analytic-circle \
        --radius 1.0 --current 1.0e6 --n-points 512 --z 0.0 /tmp/c1.simple"
  Then /tmp/c1.simple exists and its first line is "513"
  And it has exactly 514 lines in total
  And every row after line 1 has four whitespace-separated floats
  And rows 2..513 all carry current 1.0e6
  And row 514 repeats row 2's x, y, z to within 1.0e-12 and carries current 0.0

Scenario: Single converted coil reproduces the exact polygon field at its centre
  Given /tmp/c1.simple from the previous scenario
  When test_simsopt_coils.x calls create_coils_field('/tmp/c1.simple', field)
       and field%evaluate([0.0d0, 0.0d0, 0.0d0], Acov, hcov, Bmod)
  Then Bmod equals 6283.264161d0 Gauss to within 1.0d-10 relative
  And Bmod equals 6283.185307d0 Gauss to within 5.0d-5 relative

Scenario: Discretization error falls as N^-2
  Given the same coil written at --n-points 128 and at --n-points 512
  When Bmod is evaluated at the centre for each
  Then abs(Bmod_128 - 6283.185307d0) / abs(Bmod_512 - 6283.185307d0)
       equals 16.0 to within 1.0d-2 relative

Scenario: Multi-filament separation carries no spurious joining current
  Given two coaxial 512-segment coils at z = -0.5 m and z = +0.5 m,
        each of radius 1.0 m and current 1.0e6 A, written to /tmp/c2.simple
  Then /tmp/c2.simple's first line is "1026"
  And row 514 (the close point of coil 1) carries current 0.0
  When the field is evaluated at [0.0d0, 0.0d0, 0.0d0]
  Then Bmod equals 8991.807994d0 Gauss to within 1.0d-9 relative
  And Bmod equals 8991.762856d0 Gauss to within 5.0d-5 relative

Scenario: SIMSOPT JSON coil set converts to the same point-file format
  Given the committed fixture test/tests/data/simsopt_coils_ncsx.json,
        generated by test/tests/data/make_simsopt_coils_fixture.py
  When I run "python3 tools/simsopt_json_to_coils.py \
        test/tests/data/simsopt_coils_ncsx.json /tmp/c3.simple --n-points 256"
  Then the exit status is 0
  And the number of zero-current rows equals the number of Coil objects
      recorded in test/tests/data/simsopt_coils_ncsx.PROVENANCE.md
  And the first line equals 257 * that coil count

Scenario: field_from_file gives an actionable message for a .json field_input
  Given field_input = 'quasr_device.json' in simple.in
  When ./build/simple.x simple.in runs
  Then it does not print 'field_from_file: Unknown file name format'
  And stdout contains the string 'tools/simsopt_json_to_coils.py'
  And the process exits non-zero
```

## Implementation plan

The work splits into two layers that must be landed and tested independently, because layer B depends on a schema this checkout does not contain.

### Layer A — point-file writer and analytic tests (no SIMSOPT dependency)

1. **Create `tools/simsopt_json_to_coils.py` with its writer half first.** Mirror the CLI style of `tools/quasr_json_to_boundary.py` (`argparse`, `pathlib`, module-level functions, `main()`). Required now:
   - `write_coils_file(path, filaments)` where `filaments` is a list of `(points_Nx3_metres, current_amperes)`. For each filament write the closed polyline — the `N` distinct points, then the first point repeated — giving the coil current on all rows except the repeated last row, which gets `0.0`. Line 1 is the total row count across all filaments. Emit SI metres and amperes; the CGS conversion is SIMPLE's job (`src/field/field_coils.f90:48-56`).
   - An `--analytic-circle` mode taking `--radius`, `--current`, `--n-points` (default 256) and `--z`, used only by the tests. This is what makes layer A independently verifiable.
   - `--help` documents the four-column format, the zero-current separator convention, and states the SI contract explicitly.
2. **Extend the dispatcher in `src/field.F90`.** In `field_from_file`, add a branch immediately before the final `else` at line 138: if `endswith(filename, '.json')`, print a message naming `tools/simsopt_json_to_coils.py` and the exact command to run, then `error stop`. Keep Fortran free of a JSON parser — this matches how GVEC is handled (`CLAUDE.md:51`, "SIMPLE links no GVEC library at runtime"; `DOC/coordinates-and-fields.md:276`, "and links no GVEC library; convert with `tools/gvec_to_boozer_chartmap.py`"). Direct in-process ingestion, if ever wanted, is a separate PR.
3. **Add `test/tests/magfie/test_simsopt_coils.f90`.** A `program` that calls `create_coils_field` on files produced by the `--analytic-circle` mode and asserts BDD scenarios 2, 3 and 4 with the numeric constants tabulated above. Build it in `test/tests/magfie/CMakeLists.txt` alongside the existing coil tests:
   ```cmake
   add_executable(test_simsopt_coils.x test_simsopt_coils.f90)
   target_link_libraries(test_simsopt_coils.x simple)
   ```
   Unlike `test_magfie_coils.x` and `test_coils_field_compare.x`, this one **must** get an `add_test`, following the `add_test(NAME ... COMMAND $<TARGET_FILE:...>)` pattern already used further down that file. Guard the fixture-generating `add_custom_command` on `SIMPLE_ENABLE_PYTHON_TOOLS` (option declared at `CMakeLists.txt:78`), exactly as the STELLOPT converter is at `test/tests/CMakeLists.txt:259`.
4. **Add `test/tests/test_simsopt_json_to_coils.py`.** Pure-Python unit test of the writer: header count, total line count, trailing-zero-current row, first/last point coincidence, SI magnitudes, multi-filament row arithmetic. Register it in `test/tests/CMakeLists.txt` inside the existing `if(SIMPLE_ENABLE_PYTHON_TOOLS)` block, copying the shape at lines 453-461:
   ```cmake
   add_test(NAME test_simsopt_json_to_coils
       COMMAND ${Python3_EXECUTABLE}
           ${CMAKE_CURRENT_SOURCE_DIR}/test_simsopt_json_to_coils.py
       WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
   set_tests_properties(test_simsopt_json_to_coils PROPERTIES
       LABELS "unit;python")
   ```
   Use the label `"unit;python"`. There is **no** `fast` label in this repository — `grep -o 'LABELS "[^"]*"' test/tests/CMakeLists.txt | sort -u` lists the full set (`unit`, `integration`, `system`, `physics`, `slow`, `python`, `plot`, `golden_record;regression`, ...).

### Layer B — SIMSOPT JSON front-end

5. **Obtain the schema; do not guess it.** Add `test/tests/data/make_simsopt_coils_fixture.py`, a short generator that imports `simsopt` and calls `simsopt.save(coils, "simsopt_coils_ncsx.json")` on a small coil set (for example the coils shipped in `simsopt/tests/test_files`). Run it once in an environment that has SIMSOPT, commit **both** the generator and the resulting JSON, and record the exact `simsopt` version, the source coil set, the number of `Coil` objects, `nfp`, and a SHA-256 in `test/tests/data/simsopt_coils_ncsx.PROVENANCE.md` — following the naming and content style of the existing `test/tests/data/ncsx_freeboundary.PROVENANCE.md` (which pins `simsopt 1.10.6`, an upstream commit, and a SHA-256). The generator is not run at build time; it exists so the fixture is reproducible.
6. **Add the JSON parsing half to `tools/simsopt_json_to_coils.py`.** Parse the schema, do not import SIMSOPT at runtime — that keeps the tool dependency-free (`numpy` only). Drive every field name off the committed fixture, not off memory:
   - Walk `obj["simsopt_objs"]`, collect keys prefixed `Coil`, and resolve each coil's curve and current references through the same `dofs["value"]` indirection used at `tools/quasr_json_to_boundary.py:32-33`.
   - Support the curve types actually present in the fixture; evaluate each on a uniform grid in the curve parameter with `--n-points` points, then hand the result to `write_coils_file`.
   - Resolve current objects to a scalar amperage per coil.
   - Raise a clear `ValueError` naming the unhandled key for any object class not covered. Do **not** silently skip.
   - **Field-period / stellarator-symmetry expansion is explicitly out of scope for this PR.** If the fixture contains rotation or reflection wrappers, expand them only if the fixture lets you verify the result; otherwise error out and open a follow-up issue. Getting the current sign wrong under stellarator symmetry is the one genuine correctness hazard here and it should not ride along untested.
7. **Document in `DOC/coordinates-and-fields.md`.** Extend §3.3 "Coils Field" (heading at line 252) with a "SIMSOPT / QUASR input" subsection giving the converter command and the SI contract, and add a note to the `field_input` row of the table at line 941 stating that `.json` is not read directly and must be converted.
8. **No libneo change is required.** `load_coils_from_file` and the Hanson–Hirshman evaluator already accept everything this produces. A native SIMSOPT-JSON reader in Fortran would belong in `libneo/src/field/biotsavart.f90` and would need a JSON dependency there first — do not open that door in this PR.

## Acceptance criteria

- [ ] `python3 tools/simsopt_json_to_coils.py --analytic-circle --radius 1.0 --current 1.0e6 --n-points 512 --z 0.0 /tmp/c1.simple` exits 0 and writes a file whose first line is `513` and which has 514 lines.
- [ ] The last row of `/tmp/c1.simple` repeats row 2's coordinates and has current `0.0`.
- [ ] `make CONFIG=Fast && make test TEST=test_simsopt_coils` passes.
- [ ] `make test TEST=test_simsopt_json_to_coils` passes.
- [ ] Single-loop centre field equals `6283.264161 G` (exact 512-gon) to `<= 1e-10` relative, and equals the circular-loop `6283.185307 G` to `<= 5e-5` relative.
- [ ] The centre-field error against the circular limit falls by a factor `16.0 +/- 1%` between `--n-points 128` and `--n-points 512`.
- [ ] Two-coil case equals `8991.807994 G` to `<= 1e-9` relative, proving the zero-current separator row works.
- [ ] Running `./build/simple.x` with `field_input` ending in `.json` prints a message containing `tools/simsopt_json_to_coils.py`, not `Unknown file name format`.
- [ ] `test/tests/data/simsopt_coils_ncsx.json` and its `.PROVENANCE.md` are committed, the provenance names the exact `simsopt` version and coil count, and `python3 tools/simsopt_json_to_coils.py test/tests/data/simsopt_coils_ncsx.json /tmp/c3.simple --n-points 256` exits 0.
- [ ] `make test-golden` shows no change in `albert_coils` or `meiss_coils` — this PR must not touch the STELLOPT path or `create_coils_field`.
- [ ] `make test-smoke` still passes (libneo reverse-dependency gate).

## References

- Landreman, Medasani, Wechsung, Giuliani, Jorge, Zhu (2021), *SIMSOPT: A flexible framework for stellarator optimization*, Journal of Open Source Software **6**(65), 3525 — the framework whose serialization format is being consumed.
- Hanson & Hirshman (2002), *Compact expressions for the Biot-Savart fields of a filamentary segment*, Physics of Plasmas **9**, 4410 — the exact straight-segment formula libneo implements, cited in `libneo/src/field/biotsavart.f90:90`. Because it is exact for straight segments, the polygon acceptance tolerance can be as tight as `1e-10`; the remaining `1e-5`-scale error is polygon-vs-circle discretization, not formula error.
- Landreman & Paul (2022), *Magnetic fields with precise quasisymmetry for plasma confinement*, Physical Review Letters **128**, 035001 — the configurations behind the `wout_LandremanPaul2021_*` fixtures already used throughout `test/tests/CMakeLists.txt`.
- Albert, Kasilov, Kernbichler (2020), *Symplectic integration with non-canonical quadrature for guiding-center orbits in magnetic confinement devices*, Journal of Computational Physics **403**, 109065 — SIMPLE's integrator, the consumer of whatever field this issue adds.
- The regular-polygon centre and axial field expressions used above are elementary Biot-Savart results; no specific literature reference is needed, and they are reproducible from the finite-straight-wire formula.

## Scope and risk

Layer A is a single small PR, `size/S`–`size/M`: one new Python tool with an analytic mode, one Fortran test, one Python test, CMake wiring in two files, one added `else if` branch in `field_from_file`, and a documentation section. Risk is low and well-contained — nothing else in `src/` changes, and the new branch only fires on a filename that currently aborts anyway, so `albert_coils` and `meiss_coils` golden records cannot move.

Layer B should be a second PR, because it cannot be written or reviewed without a real SIMSOPT JSON coil fixture in hand. Splitting also keeps the symmetry-expansion hazard (rotation, reflection, current sign) out of the first merge; that expansion is deliberately deferred to a follow-up issue.

Related open issues, all verified: `itpplasma/SIMPLE#39` ("Test SIMPLE losses as optimization target in SIMSOPT") and `itpplasma/SIMPLE#27` ("Test metrics in simsopt") are downstream consumers of this capability, not duplicates — both assume a SIMSOPT-defined configuration can already be traced. `itpplasma/sensopt#60` ("QUASR geometry/QS loader and metric table (no stored alpha-loss)") parses the same QUASR JSON archive, though for geometry and quasisymmetry metrics in a different repo; worth aligning the `simsopt_objs` parsing conventions with whoever lands first. `itpplasma/libneo#19` ("Replace pfile format by mgrid format") is adjacent but *not* an alternative to this work: it concerns `bdivfree`/`coil_tools` and the tokamak vacuum-perturbation `pfile`, not SIMPLE's stellarator filament path. A grid-based (`mgrid`) route to a SIMSOPT field is conceivable as a separate design, but no in-tree work tracks it.
